eldenring_propositions = ["Lore in Elden Ring covers all the information related to the world of Elden Ring.",
"Lore in Elden Ring covers all the information related to the mythos of Elden Ring.",
"Lore in Elden Ring includes past events that occurred long ago.",
"Lore in Elden Ring includes the history of the Lands Between.",
"Lore in Elden Ring includes the mystery of the elusive Elden Ring.",
"All information related to past events, the history of the Lands Between, and the mystery of the Elden Ring can be found in the lore.",
"This page contains heavy spoilers.",
"The Mythos of Elden Ring was written by George R. R. Martin.",
"Mythos refers to the overall narrative theme or plot structure.",
"Mythos can also be interpreted as a belief system.",
"The Story of Elden Ring was written by Hidetaka Miyazaki.",
"Hidetaka Miyazaki was part of a team at FromSoftware.",
"The Lore and Story of Elden Ring are told in a similar manner to other FromSoftware 'Souls' games.",
"Players should expect to find plenty left to interpretation in Elden Ring.",
"Players should expect to find seemingly contradictory statements about various game characters in Elden Ring.",
"Players should expect to find seemingly contradictory statements about various game elements in Elden Ring.",
"Players should expect to find seemingly contradictory statements about various game concepts in Elden Ring.",
"Elden Ring is a video game.",
"Elden Ring has a lore overview.",
"The storyteller folds her slender hands.",
"The storyteller folds both pairs of her hands.",
"The storyteller speaks.",
"The storyteller states that the events happened an age ago.",
"The storyteller recalls the events and sees them as true.",
"The tale of the Shattering begins.",
"The Shattering is a devastating war between the children of Marika.",
"The children of Marika are Demigods of the Lands Between.",
"One grim night in the depths of winter, a flock of unknown assassins stole across the Lands Between.",
"In a coetaneous attack, the foul covenant snuffed out the lives of many of the God-Queen’s kin throughout the empire.",
"The number of the God-Queen’s kin was too numerous and too scattered for her godly protection to save.",
"The assassins’ targets were multifold.",
"None of the targets was as devastating a loss to the Eternal Queen as that of Godwyn the Golden.",
"After the death of Godwyn the Golden, the Elden Ring was somehow shattered.",
"The order of the world broke with the shattering of the Elden Ring.",
"Out of the chaos came war.",
"The war was open and bitter.",
"The war pitted blood against blood and kin against kin.",
"The conflict broke a vast and prosperous empire into brittle fragments.",
"No single side could find enough purchase to maintain a decisive victory.",
"The power of a Great Rune fueled the conflict.",
"The battle of General Radahn against Malenia the Severed illustrated that neither strength nor skill alone would be enough to take control of the entirety of the lands Marika had united.",
"The Lands Between are no longer gripped by open war.",
"The Lands Between are caught in an uneasy stalemate that seems impossible to resolve.",
"The storyteller suggests that one could take the crown.",
"George R.R. Martin is the author of The New York Times best-selling fantasy series, A Song of Ice and Fire.",
"FromSoftware created a world based on the work of George R.R. Martin.",
"A new trailer is available for the mythology of George R.R. Martin and the world created by FromSoftware.",
"The audience will be transported to ages long ago.",
"The audience will relive the Shattering.",
"The Shattering is a war that brought darkness to the Lands Between.",
"The Shattering was initiated by the demigods’ hunger for power.",
"The audience will fight alongside General Radahn and Malenia the Severed.",
"Even General Radahn and Malenia the Severed couldn’t reunite a world so badly broken.",
"There is only one hope left: the hope that a new Elden Lord will rise.",
"The new Elden Lord will lift the veil of shadows that has fallen over Marika’s domain.",
"The wait for the audience is almost over.",
"Soon the audience will venture into the Lands Between.",
"The audience will strive to become the Elden Lord.",
"The audience is addressed as Tarnished.",
"The audience is encouraged to prepare to claim what fate has promised them.",
"The Lands Between is the world of Elden Ring.",
"Those who live in The Lands Between were blessed by Grace through the Elden Ring.",
"Those who live in The Lands Between were blessed by Grace through the Erdtree.",
"Those who were blessed by the Elden Ring are characterized by having a golden aura that can be seen in their eyes.",
"At some point, some of those who were blessed lost their grace.",
"Those who lost their grace were exiled.",
"Those who were exiled were labeled the Tarnished.",
"At some point, the Elden Ring was shattered.",
"The shards of the Elden Ring were scattered across the Lands Between.",
"The largest of the shards were called Great Runes.",
"The Great Runes were claimed by the six Demigod children of Queen Marika the Eternal.",
"The six Demigod children of Queen Marika the Eternal inherited different powers.",
"The six Demigod children of Queen Marika the Eternal have been physically changed and twisted due to being corrupted by the power of the Great Runes.",
"The Lands Between is divided into 7 distinct areas.",
"Limgrave is one of the areas in the game.",
"Caelid is one of the areas in the game.",
"Liurnia of the Lakes is one of the areas in the game.",
"Altus Plateau is one of the areas in the game.",
"Mt. Gelmir is one of the areas in the game.",
"Mountaintops of the Giants is one of the areas in the game.",
"The River Kingdoms is an underground area in the game.",
"Each area is overseen by a Demigod.",
"The game features a central 'overworld' that connects all of these areas.",
"According to an interview with Hidetaka Miyazaki, players will have total freedom as to the order they want to tackle for each area.",
"It is up to the player on how they want to approach each area.",
"The hub area is similar to Firelink Shrine or Majula in previous games.",
"The hub area will not be accessible at the beginning of the game.",
"Players will need to progress the game until they reach the hub area.",
"Elden Ring is a video game.",
"Elden Ring features various characters.",
"The characters in Elden Ring have lore.",
"The lore of the characters in Elden Ring provides background information.",
"The background information enhances the player's understanding of the characters.",
"Hidetaka Miyazaki is a game designer.",
"Hidetaka Miyazaki states that The Lands Between is supposed to invoke a feeling of something that is very mysterious and very ethereal.",
"Hidetaka Miyazaki hopes that players will experience the mysterious and ethereal feeling when they play the game.",
"In the opening of the official reveal trailer presented in E3 2021, a softly spoken, hooded woman says 'The Tarnished will soon return.'",
"The question is who and what is The Tarnished.",
"Simply put, the player is the Tarnished.",
"As the player, the player is one of the Tarnished that have been exiled upon losing their blessing of Grace.",
"The blessing of Grace is granted by the Elden Ring.",
"The Elden Ring is associated with the Erdtree.",
"The Erdtree is a tree that hosts the source and life of The Lands Between.",
"The player is similar to characters in previous Souls games, such as the Chosen Undead or the Ashen One.",
"After the shattering of the Elden Ring, the player is called back by the lost Grace to The Lands Between.",
"The player is called back along with other Tarnished to recover the shards of the Elden Ring.",
"The goal is to make the shards of the Elden Ring whole once again.",
"The player aims to become the Elden Lord of The Lands Between.",
"Hidetaka Miyazaki states in an interview that one of the main themes of the game is how the player, the Tarnished, approaches or treats the newfound grace.",
"Hidetaka Miyazaki emphasizes the return to the land that the Tarnished were once banished from.",
"Hidetaka Miyazaki mentions that many characters in the game are beckoned back and will have their own adventures and motives.",
"Hidetaka Miyazaki wants the player to discover for themselves what the newfound grace means.",
"Hidetaka Miyazaki encourages players to determine how they want to begin their adventure.",
"Melina is one of the first people the Tarnished encounters on their journey.",
"Melina maintains an air of mystery throughout the game.",
"Melina does not have a physical form.",
"Melina acts as the Tarnished's Finger Maiden in exchange for taking Melina to the Erdtree.",
"Melina later asks the Tarnished to take her to the Mountaintops of the Giants.",
"Melina approaches the Tarnished to aid Melina in her search for her purpose.",
"Melina believes her purpose was given to her by her mother.",
"Melina believes her mother can be found at the base of the Erdtree.",
"Many speculate that Melina's mother is Marika.",
"When summoned, Melina wields the Blade of Calling.",
"The Blade of Calling is a dagger that was previously owned by the kindling maiden.",
"The ownership of the Blade of Calling is fitting considering Melina's role as kindling when the Erdtree is burnt down.",
"Speaking with Melina at various Sites of Grace reveals Melina's ability to recall echoes of Queen Marika's past actions and words.",
"Melina offers echoes of Queen Marika's past actions and words in lieu of a 'maiden's guidance'.",
"Melina holds contempt for the Frenzied Flame.",
"Melina believes that whoever lords over the chaos and damage brought by the Frenzied Flame is no Lord at all.",
"If the Tarnished takes the Frenzied Flame before the event at the Forge of the Giants, Melina will leave the Tarnished.",
"Melina will threaten to deliver the Tarnished Destined Death once the Tarnished becomes Lord of the Frenzied Flame.",
"The White Masks encountered in Mohgwyn Palace were initially abducted by Mogh.",
"Mogh was the Lord of Blood.",
"The White Masks were turned into Bloody Fingers through an unknown ritual.",
"The unknown ritual involved Mogh's accursed Omen blood.",
"Of the four White Masks, the Tarnished encounters in the game, only Varre was able to withstand and tame the accursed blood.",
"Varre was abducted by the Lord of Blood.",
"Varre remains loyal to the Mohgwyn Dynasty.",
"Varre tries to indoctrinate the Tarnished into the Mohgwyn Dynasty.",
"Varre is dying at the end of his questline.",
"Varre is forsaken by his Lord.",
"Varre calls out to Mohg at the end of his questline.",
"Varre blesses the Mohgwyn Dynasty.",
"Bloody Finger Hunter Yura is a samurai from the Land of Reeds.",
"Bloody Finger Hunter Yura's purpose is to hunt down Bloody Fingers.",
"Bloody Finger Hunter Yura's biggest target is Eleonora.",
"Eleonora is known as the Violet Bloody Finger.",
"Eleonora is a Tarnished whom Bloody Finger Hunter Yura holds in high regard.",
"It is uncertain what exactly caused Eleonora's corruption into a Bloody Finger.",
"Bloody Finger Hunter Yura warns the Tarnished against the dangers of Dragon Communion.",
"Bloody Finger Hunter Yura states that those who partake in Dragon Communion one day lose their humanity.",
"Other Bloody Fingers that the Tarnished encounter are targets of Bloody Finger Hunter Yura.",
"Some of the other Bloody Fingers have been approached and swayed by Mohg.",
"Mohg is known as the Lord of Blood.",
"Sorcerer Rogier is a Tarnished.",
"Sorcerer Rogier has an easy-going nature.",
"Sorcerer Rogier is said to be a wise and powerful sorcerer by his old travelling companion, D.",
"Sorcerer Rogier was once a scholar.",
"Sorcerer Rogier was seeking the truth behind the Night of the Black Knives.",
"Sorcerer Rogier's scholarly pursuits eventually brought him under Stormveil Castle.",
"Sorcerer Rogier found and disturbed a corpse under Stormveil Castle.",
"Disturbing the corpse caused Sorcerer Rogier to be afflicted with Death.",
"D sees Those Who Live in Death as a threat against the Golden Order.",
"Sorcerer Rogier is empathetic towards Those Who Live in Death.",
"Sorcerer Rogier believes Those Who Live in Death have committed no offence.",
"By finishing Sorcerer Rogier's quest, the Tarnished is able to help Sorcerer Rogier reveal many insights about the night of the assassination.",
"Sorcerer Rogier finally succumbs to his affliction.",
"Fia is a Tarnished Deathbed Companion.",
"Fia was driven from her home when awoken by the guidance of grace.",
"Fia describes a Deathbed Companion as a person who receives warmth and life from numerous champions.",
"A Deathbed Companion lays with the remains of an exalted noble to revive them.",
"Fia says the act of laying with the remains of an exalted noble is revered in her homeland.",
"Fia is empathetic towards Those Who Live in Death.",
"Fia has put it upon herself to be the guardian of Those Who Live in Death.",
"Before meeting Fia at Deeproot Depths, the Tarnished will encounter Fia's champions.",
"One of Fia's champions is Rogier.",
"Another of Fia's champions is Lionel the Lionhearted.",
"Lionel the Lionhearted is a knight Fia met on her journey to the Lands Between.",
"Lionel the Lionhearted declared himself to be Fia's father.",
"Fia brings together Ranni's half of the Cursemark of Death from the Divine Tower of Liurnia.",
"Fia brings together Godwyn's half of the Cursemark of Death from D.",
"Fia implies that being Godwyn's Deathbed Companion will have Godwyn be reborn as a rune.",
"The rune representing Those Who Live in Death is called the Mending Rune of the Death-Prince.",
"D is a devout follower of the Golden Order.",
"D hunts Those Who Live in Death.",
"D notably hunts Tibia Mariners for their Deathroot.",
"D has a twin brother.",
"The dialogue of D's twin brother suggests that his name is Darian.",
"D and Darian have separate bodies.",
"D and Darian have separate minds.",
"D and Darian share the same soul.",
"One twin cannot be conscious when the other is conscious.",
"Other Orders would have seen D and Darian as cursed beings.",
"The two twins found comfort in the Golden Order.",
"The Golden Order is the one Order that does not see D and Darian as cursed beings.",
"D states that Those Who Live in Death go against the principles of the Golden Order.",
"D believes that Those Who Live in Death must be exterminated.",
"D is known as the Beholder of Death.",
"D has a twin brother.",
"The name of D's twin brother is inferred to be Devin from D's voicelines.",
"Devin can be found slumbering in the Siofra Aqueduct while D is alive.",
"Devin can be found grieving in the Siofra Aqueduct when D is dead.",
"Devin is unable to talk and interact with D.",
"Despite the inability to talk and interact, D and Devin seem to be close.",
"Devin swears revenge against D's killer.",
"D's killer may be Fia or the Tarnished.",
"Devin swears revenge when given D's armor set.",
"Gurranq is a large beastman who hungers for Deathroot.",
"Before meeting the Tarnished, D was in charge of hunting for and providing Gurranq with Deathroot.",
"It is heavily implied that the Beast Clergyman encountered by the Tarnished in Crumbling Farum Azula is Gurranq.",
"Gurranq recognizes the Tarnished if the Tarnished has given him all 9 Deathroot.",
"It is implied that Gurranq is Maliketh, the Black Blade.",
"Maliketh is Marika's Shadow.",
"Maliketh was bestowed upon Marika by the Greater Will as an Empyrean.",
"Blaidd is to Ranni as Maliketh is to Marika.",
"According to the Stone of Gurranq, Maliketh was a ferocious warrior.",
"Maliketh's name meant 'Death of the Demigods'.",
"Marika ordered Maliketh to lock away the Rune of Death.",
"The Rune of Death is also referred to as Destined Death.",
"A fragment of the Rune of Death was stolen and used in the Night of the Black Knives.",
"The Night of the Black Knives led to the death of the first demigod, Godwyn the Golden.",
"To ensure the Rune of Death was never stolen again, Maliketh bound his sword within his own body.",
"Maliketh's sword was imbued with the Rune of Death.",
"Maliketh changed his name after binding his sword within his own body.",
"Maliketh's Remembrance implies that he was betrayed by Marika.",
"The exact matter of Maliketh's betrayal by Marika is unknown.",
"Roderika is a Tarnished driven away from her home across the sea.",
"The cloak worn by Roderika implies that she used to be a member of royalty.",
"At some point upon arriving at the Lands Between, Roderika happened upon White Mask Varre.",
"White Mask Varre gave Roderika the same advice as he gives the Tarnished at the beginning of their journey.",
"White Mask Varre advised Roderika to seek Godrick and his Great Rune at Stormveil Castle.",
"Upon arriving at Stormhill, the men escorting Roderika were taken and sacrificed for grafting.",
"Roderika feels guilt about the fact that she is too afraid to join the men who were sacrificed.",
"Roderika moves to the Roundtable Hold to find purpose after receiving the hopeful echoes of her men through the Chrysalids' Memento.",
"Smithing Master Hewg recognises Roderika's potential for spirit tuning through her eyes.",
"With a bit of encouragement from the Tarnished, Smithing Master Hewg trains Roderika to be a skillful spirit tuner.",
"Roderika and Smithing Master Hewg become close.",
"Even as the Roundtable Hold is burning down, Roderika stays behind with Smithing Master Hewg to repay his kindness.",
"Smithing Master Hewg is a misbegotten chained and imprisoned at the Roundtable Hold.",
"Smithing Master Hewg is tasked by Queen Marika to smith a weapon strong enough to kill a god.",
"Smithing Master Hewg makes the task of smithing a weapon strong enough to kill a god his life goal.",
"Smithing Master Hewg strongly believes that the Tarnished will be the one to become Elden Lord.",
"Smithing Master Hewg will express his belief about the Tarnished becoming Elden Lord before he completely loses his memory.",
"Nepheli Loux is the adoptive daughter of Sir Gideon Ofnir.",
"Sir Gideon Ofnir took Nepheli Loux in when Nepheli Loux lost the guidance of grace.",
"Nepheli Loux became a Tarnished.",
"Nepheli Loux is a skilled warrior.",
"Nepheli Loux believes in standing up and enacting justice for the weak and oppressed.",
"Nepheli Loux once believed that Sir Gideon Ofnir held the same beliefs.",
"Nepheli Loux learned that Sir Gideon Ofnir was the mastermind behind the attack on the Village of the Albinaurics.",
"After learning the truth about Sir Gideon Ofnir, Nepheli Loux loses faith in him.",
"It is speculated that Nepheli Loux has ties with the first Elden Lord, Godfrey.",
"Nepheli Loux is speculated to be connected to the Golden Lineage.",
"Nepheli Loux bears the same last name as Hoarah Loux.",
"Kenneth Haight deems Nepheli Loux worthy of taking up the mantle of leader of Limgrave.",
"Kenneth Haight is a member of the Erdtree royalty.",
"Kenneth Haight is a self-proclaimed rightful leader of Limgrave.",
"Kenneth Haight is the owner of Fort Haight.",
"Kenneth Haight looks down on Godrick.",
"Kenneth Haight deems Godrick unworthy of ruling Limgrave.",
"Kenneth Haight believes Godrick's actions during the Shattering were cowardly.",
"Kenneth Haight believes Godrick does not possess the proper lineage required to rule.",
"Kenneth Haight took back Fort Haight from Godrick's forces.",
"Kenneth Haight saw the state Fort Haight has been left in.",
"Kenneth Haight laments that he does not have the authority to rule Limgrave.",
"Kenneth Haight goes on to look for an eligible candidate to rule Limgrave.",
"Kenneth Haight finally comes across Nepheli Loux.",
"Gostoc is the Gatekeeper of Stormveil Castle.",
"Gostoc informs the Tarnished of a safer side passage to allow the Tarnished to enter Stormveil Castle undetected.",
"Gostoc can be caught sneaking and following the Tarnished around in Stormveil Castle.",
"Each time the Tarnished are defeated, Gostoc steals a portion of the Golden Runes that the Tarnished drop.",
"Gostoc seems to do this with each Tarnished that comes to Stormveil Castle to challenge the shardbearer.",
"Gostoc holds contempt for Godrick, the master of Stormveil Castle.",
"Gostoc has been mistreated and looked down upon by Godrick.",
"Much of Gostoc's dialogue reveals that Gostoc longs for freedom from Godrick and his duties.",
"When Nepheli takes the throne, Gostoc is happy to return to his duties.",
"Boc is a seamster.",
"Boc is a demi-human outcast.",
"Boc is often picked on for his looks.",
"Boc looks up to his late mother.",
"Boc's late mother was a skilled seamstress.",
"Boc's late mother was one of the few people who cared for him.",
"Boc was kicked out of his former home in the Costal Cave.",
"Boc had his possessions stolen by other demi-humans.",
"The Tarnished helps Boc take back his prized Sewing Needle.",
"The Tarnished helps Boc take back his Tailoring Tools.",
"Boc offers to tailor the Tarnished's armor as compensation.",
"Boc expresses unhappiness towards his looks throughout his interactions with the Tarnished.",
"The Tarnished can grant Boc a Larval Tear to help change his appearance.",
"The Tarnished can let Boc know he is accepted.",
"Both granting a Larval Tear and letting Boc know he is accepted result in Boc being grateful.",
"Brother Corhyn is a cleric of the Golden Order.",
"Brother Corhyn's armor implies that he once foretold an inauspicious prophecy.",
"The details of the inauspicious prophecy foretold by Brother Corhyn are unclear.",
"Throughout his questline, Brother Corhyn shows high and unwavering faith in the Golden Order.",
"Brother Corhyn is greatly interested in discovering the secrets of the Golden Order.",
"Brother Corhyn leaves the Roundtable in search of Goldmask.",
"Goldmask is a great scholar of Golden Order fundamentalism.",
"After introducing Brother Corhyn to Goldmask, Brother Corhyn acts as Goldmask's scribe.",
"Brother Corhyn translates and records Goldmask's various finger movements into written records.",
"Brother Corhyn holds Goldmask in high regard.",
"After learning of Goldmask's reservations towards the Golden Order, Brother Corhyn begins to question Goldmask's intentions.",
"Goldmask is a famed scholar of Golden Order fundamentalism.",
"Goldmask is one of many Tarnished called back to the Lands Between after the Shattering.",
"Goldmask does not speak.",
"Goldmask communicates through rhythmic hand and finger movements.",
"Goldmask once lamented that hunters of Those Who Live in Death had been reduced to fanatics of the Golden Order.",
"Goldmask lamented that hunters of Those Who Live in Death hunted simply for the sake of having an evil to fight against.",
"Throughout his questline, the Tarnished aids Goldmask in better understanding the Golden Order.",
"The Tarnished aids Goldmask most notably in the nature of Radagon.",
"The Tarnished aids Goldmask to correct the imperfections that lie within the Golden Order.",
"With the Mending Rune of Perfect Order, Goldmask concluded that the imperfections found were due to the very gods being just as fickle as ordinary men.",
"Gowry is a Kindred of Rot disguised as an old sage.",
"Gowry was Millicent's caretaker as a child.",
"It is uncertain what or where Gowry's real form is.",
"Gowry returns to his shack as he was before most times after being attacked.",
"After Malenia's Scarlet Aeonia bloomed in Caelid during the Shattering, Gowry dedicated his services to Malenia.",
"Gowry believes Malenia to be the one to bring about a new order.",
"The new order that Gowry believes in is the Order of Rot.",
"In the swamp of Aeonia, Gowry found Millicent as a baby.",
"Gowry presumably found Millicent's sisters as babies in the swamp of Aeonia.",
"Gowry proceeded to raise Millicent and her sisters.",
"Gowry hoped that when Malenia ascended to be the Goddess of Rot, Millicent and her sisters would be reborn as scarlet valkyries.",
"Of all the sisters, Gowry saw the most potential in Millicent to follow in Malenia's footsteps.",
"At the end of Millicent's quest, Gowry asks the Tarnished to aid Millicent's sisters in attacking Millicent.",
"Gowry believes that the betrayal Millicent feels from the person she trusted the most will act as a catalyst for her to 'bloom'.",
"Millicent is a daughter of Malenia.",
"Millicent shares many striking similarities with her mother.",
"Millicent has bright red hair.",
"Millicent has a missing arm due to her severe scarlet rot affliction.",
"Millicent possesses skilled swordsmanship that resembles her mother's style.",
"Millicent feels a sense of familiarity within Gowry's Shack due to the scarlet rot.",
"Millicent does not remember her childhood with Gowry.",
"Millicent is cured using the Unalloyed Golden Needle.",
"After being cured, Millicent sets out on a journey to seek Malenia.",
"Millicent hopes to aid Malenia in resisting the call of the scarlet rot.",
"Before Millicent is able to reach the Empyrean, she is ambushed by her sisters at Elphael.",
"Millicent may be ambushed by the Tarnished if they choose to do so.",
"If the Tarnished defends Millicent instead, Millicent reveals that she is aware of what Gowry hoped she would bloom into.",
"Millicent removes the golden needle.",
"Millicent succumbs to the scarlet rot.",
"Millicent does not want to live as someone other than herself.",
"Irina is the blind daughter of Edgar.",
"Edgar is the Commander of Castle Morne.",
"The Tarnished meets Irina after crossing the Bridge of Sacrifice to the Weeping Peninsula.",
"Irina escaped Castle Morne with the help of her father and some attendants at the castle.",
"The Misbegotten serving under Castle Morne rebelled.",
"Irina cares much for her father.",
"Irina implores the Tarnished to deliver a letter persuading Edgar to leave Castle Morne.",
"Irina's reunion with her father unfortunately never happens.",
"Irina gets murdered.",
"A large sword is left by Irina's corpse.",
"It is implied that an escaped Misbegotten from Castle Morne was Irina's killer.",
"Edgar is the Commander of Castle Morne.",
"Edgar was ordained by Godrick.",
"Edgar has a high sense of duty.",
"Edgar stays behind to protect the castle's prized sword.",
"The castle's prized sword is the Grafted Blade Greatsword.",
"The rest of the castle's attendants fled from the Misbegotten rebellion.",
"Edgar expresses regret over not protecting Irina after finding her body.",
"Edgar swears vengeance towards Irina's killers.",
"Edgar can later be found at Revengers Shack as an invader.",
"Edgar drops a Shabriri Grape.",
"It is speculated that Edgar succumbed to madness from Irina's death.",
"Hyetta is a blind young woman.",
"Hyetta resembles Irina.",
"Hyetta is able to perceive some form of light every time Hyetta consumes a Shabriri Grape.",
"Hyetta is initially disgusted by the fact that Shabriri Grapes are human eyes.",
"Hyetta quickly comes to terms with the fact that Shabriri Grapes are human eyes.",
"Hyetta affirms that consuming Shabriri Grapes is required for Hyetta to become a finger maiden.",
"The Tarnished is not the only person bringing Hyetta Shabriri Grapes.",
"Hyetta mentions that other beings with trembling hands and emaciated fingers have given Hyetta the grapes before.",
"Successfully completing the quest for Hyetta aids Hyetta in becoming a Finger Maiden.",
"Successfully completing the quest for Hyetta gives the Tarnished more information on the Three Fingers.",
"Successfully completing the quest for Hyetta gives the Tarnished more information on the Frenzied Flame.",
"Shabriri is a mysterious figure who refers to himself as chaos incarnate.",
"Shabriri inhabits the body of Yura.",
"Shabriri claims that Yura willingly gave his body away.",
"The Tarnished meets Shabriri at the Mountaintops of the Giants.",
"Shabriri tries to persuade the Tarnished into becoming the Lord of Frenzied Flame.",
"Shabriri gives the Tarnished information on the Frenzied Flame Proscription.",
"Shabriri was also the name of a man who previously had his eyes gouged out as punishment for his crime of slander.",
"In time, the eyes of Shabriri were filled with the flame of frenzy.",
"According to the Howl of Shabriri, this was the first instance of the maddening sickness of frenzy in the Lands Between.",
"Ranni the Witch is the daughter of Rennala and Radagon.",
"Ranni the Witch took after her mother, Rennala.",
"Ranni the Witch discovered her own full moon, Ranni's Dark Moon.",
"Ranni the Witch learnt cold sorceries from the mysterious Snow Witch.",
"The mysterious Snow Witch was encountered by Ranni the Witch deep in the woods.",
"Ranni the Witch has held Blaidd and Iji dearly since childhood.",
"At some point, Ranni the Witch defeated the Glinstone Dragon, Adula.",
"Adula swore allegiance to Ranni the Witch after being defeated.",
"Ranni the Witch was not born a demigod.",
"Radagon's unity with Marika made Ranni the Witch eligible to be an Empyrean.",
"Ranni the Witch did not want to be controlled by the Two Fingers.",
"Ranni the Witch rejected her fate.",
"Ranni the Witch masterminded the Night of the Black Knives as an act of rebellion.",
"Ranni the Witch stole the Rune of Death.",
"Ranni the Witch imbued the power of the Rune of Death in the knives of the Black Knife Assassins.",
"On the night of the assassination, Ranni the Witch's body died.",
"Ranni the Witch's soul was transferred into a doll.",
"The doll is reminiscent of Ranni the Witch's old master, Renna, the Snow Witch.",
"Blaidd is the half-wolven Shadow of Ranni.",
"Blaidd was granted to Ranni by the Two Fingers when Ranni became an Empyrean.",
"Blaidd is an agent of the Two Fingers.",
"Blaidd's loyalties lie only with Ranni.",
"Blaidd considers Ranni as family.",
"Blaidd carries a sword called the Royal Greatsword.",
"The Royal Greatsword was imbued with cold magic as proof of Blaidd's loyalty.",
"If an Empyrean were to go against the will of the Two Fingers, their Shadow would go mad and oppose them.",
"Blaidd would eventually face the fate of going mad.",
"Even in madness, Blaidd continued to defy his fate.",
"Blaidd remained faithful to Ranni.",
"Iji is the only friendly Troll that the Tarnished encounters on their journey.",
"Iji has two roles within the Carian royal family.",
"Iji is the royal family's blacksmith.",
"According to Jerren, the blades smithed by Iji were blunt.",
"The blades smithed by Iji were able to resist decay when faced against scarlet rot.",
"Iji also acts as Ranni's war counselor.",
"Iji provides Ranni and those under her with guidance on the lost city of Nokron.",
"Iji cares very much for Blaidd.",
"Iji cares very much for Ranni.",
"Iji has watched over Blaidd and Ranni since they were children.",
"Iji is loyal towards Ranni.",
"Iji's Mirrorhelm seems to imply that Iji feared the consequence of his treachery against the Greater Will.",
"Seluvis is a magic preceptor.",
"Seluvis is in service to the Carian Royal family.",
"Seluvis is currently aiding Ranni in her search for the dark path.",
"Seluvis helped Sellen in some way when Sellen was initially exiled from the academy.",
"Sellen does not seem too fond of Seluvis when Seluvis is brought up.",
"Seluvis is prickly at first.",
"If the Tarnished discovers Seluvis's puppet collection, Seluvis reveals his scheme to betray Ranni.",
"Seluvis's scheme involves adding Ranni, a demigod, to his puppet collection.",
"It is speculated that Seluvis and Pidia have a connection.",
"Seluvis and Pidia both have affinities towards puppets.",
"Merchant Kale is one of the numerous nomadic merchants that the Tarnished can buy wares off of.",
"Merchant Kale is acquainted with Blaidd.",
"Blaidd refers to Merchant Kale as a busybody.",
"The nomads used to prosper as a group known as the Great Caravan.",
"The nomads were accused of heresy.",
"The nomads were cast deep underground to be buried alive.",
"The nomads summoned the flame of frenzy while underground.",
"Merchant Kale describes the nomadic clan as spiteful.",
"It is presumed that the nomads' summoning ritual was done out of spite.",
"The note on the Lord of Frenzied Flame implies that the nomads came to worship the frenzied flame.",
"Pieces of Merchant Kale's cut quest have been found by community members.",
"In the cut content, the Tarnished would have aided Merchant Kale in discovering what happened to the Great Caravan.",
"The quest would have led the Tarnished to the Subterranean Shunning-Grounds.",
"The quest would have specifically led the Tarnished to the Frenzied Flame Proscription.",
"Merchant Kale would comment on the bodies of the nomad clan found on the way to the underground area.",
"Merchant Kale describes the bodies as 'sick', 'maddened', 'husks of themselves', and 'hardly human anymore'.",
"Merchant Kale finds out that his people were falsely accused of worshipping the Three Fingers.",
"Merchant Kale finds out that his people were falsely accused of summoning the frenzied flame into the Lands Between.",
"The false accusations fill Merchant Kale with spite towards the Greater Will and the Golden Order.",
"Merchant Kale would have refused further trade with the Tarnished until the Tarnished inherited the frenzied flame.",
"After the Tarnished inherited the frenzied flame, Merchant Kale would try to be granted an audience with the Three Fingers.",
"Jerren is a witch-hunter.",
"Jerren was initially a nomadic wanderer.",
"Jerren happened upon being a guest to the Carian royal family.",
"During his time with the Carian royal family, Jerren was able to get acquainted with various members of the royal family.",
"Notable members of the Carian royal family that Jerren became acquainted with include Ranni, Iji, and Radahn.",
"Jerren made a promise to Ranni and Iji to slay a longstanding enemy of the Carian family.",
"The longstanding enemy of the Carian family is the Graven Witch Sellen.",
"The Graven Witch Sellen had committed atrocities against many of her fellow sorcerers.",
"Before Jerren could fulfill his promise to slay the Graven Witch Sellen, General Radahn recruited Jerren into his army.",
"Jerren served as a guest commander during the Shattering.",
"Jerren is an excellent swordsman.",
"The Flamberge that Jerren wields is one of the symbols of Redmane Castle.",
"When the Tarnished first meets Jerren, Jerren heralds the beginning of the war festival.",
"Sellen was said to be one of the most promising sorcerers in the history of the Raya Lucaria Academy.",
"Scholars whose studies were deemed worthy received a glintstone crown.",
"Sellen had a unique glintstone crown from other scholars the Tarnished encounters at the Raya Lucaria Academy.",
"Sellen was exiled from the Raya Lucaria Academy for her obsession and forbidden pursuit of the primeval current.",
"There are two speculated reasons that pursuing the primeval current is prohibited at the Raya Lucaria Academy.",
"One speculated reason is the dangers it brought to the sorcerer pursuing the primeval current.",
"During her quest, Sellen mentions two other primeval sorcerers, Master Lusat and Master Azur.",
"Master Lusat and Master Azur were both masters of glintstone sorcery banished from the Raya Lucaria Academy.",
"The minds of Master Lusat and Master Azur were broken simply by taking a glimpse into the primeval current.",
"It is also speculated that pursuing the primeval current is forbidden due to requiring human sacrifices.",
"According to Jerren, Sellen has killed many of her fellow sorcerers in her studies.",
"The Graven-School Talisman notes that fashioning the bodies of sorcerers into 'seeds of stars' is one method of pursuing the primeval current.",
"Because of her scholarly pursuits, Sellen was imprisoned in Witchbane Ruins by the Raya Lucaria Academy and the Carian Royal Family.",
"If the Tarnished chooses to aid in Sellen's quest, the Tarnished can help Sellen inhabit a new unshackled body.",
"The process of helping Sellen inhabit a new unshackled body involves transplanting her primeval glintstone into another compatible body.",
"Sellen's primeval glintstone is essentially her soul.",
"Thops is a glintstone sorcerer from the Academy of Raya Lucaria.",
"Thops was looked down upon by his fellow scholars.",
"Thops was nicknamed Thops the Bluntstone.",
"Thops was nicknamed Thops the Bluntstone for not having enough talent to cast powerful sorceries.",
"Thops longs to return to the Academy of Raya Lucaria to finish his studies.",
"If the Tarnished chooses to aid Thops in his quest, Thops is able to complete his lifelong project.",
"Thops creates the spell Thops's Barrier.",
"Thops's Barrier is a uniquely defensive glintstone sorcery.",
"Thops's Barrier is able to deflect both sorceries and incantations back at their caster.",
"Thops's Barrier is a spell that is worthy of its own conspectus.",
"Miriel is a large turtle.",
"Miriel is the steward of the Church of Vows.",
"Miriel is a peaceful soul.",
"Miriel teaches the Tarnished about Absolution.",
"Miriel does not require Absolution if the Tarnished attack him.",
"Miriel is well-versed in the history of Rennala and Radagon's union.",
"Miriel is able to teach the Tarnished all manner of sorceries and incantations.",
"Corhyn deems incantations not related to the Golden Order as heresy.",
"Miriel is open-minded towards each of the sorcery and incantation scrolls the Tarnished gives him.",
"Albus is a first generation Albinauric.",
"The first generation of Albinaurics were created with defects in their legs.",
"The defects in the legs of the first generation of Albinaurics caused them to not be able to walk.",
"According to Albus, when the legs of the first generation of Albinaurics fade, so too will their life.",
"The Tarnished finds Albus disguised as a pot.",
"Albus disguises himself as a pot to escape from Gideon's subordinates.",
"Gideon's subordinates were attacking the Village of the Albinaurics.",
"Albus safeguards the right half of the Haligtree Secret Medallion.",
"The Haligtree Secret Medallion is said to be key to reaching the promised land of the Albinaurics.",
"The promised land of the Albinaurics is Miquella's Haligtree.",
"Latenna is a first-generation Albinauric.",
"Latenna is one of many wolf-riding Albinauric archers.",
"Latenna was interrogated by an agent of Sir Gideon Ofnir.",
"It is possible that Sir Gideon Ofnir himself interrogated Latenna.",
"The interrogation was about the second half of the Haligtree Secret Medallion.",
"The interrogation led to the death of Latenna's faithful wolf, Lobo.",
"If the Tarnished approaches Latenna with the right half of the medallion, Latenna asks the Tarnished to take her to Apostate Derelict.",
"Latenna offers the whereabouts of the left half of the secret medallion in exchange for being taken to Apostate Derelict.",
"Upon arriving at Apostate Derelict, Latenna transfers a birthing droplet to a large Albinauric called Phillia.",
"It is unclear what exact purpose the birthing droplet has.",
"Latenna mentions that the birthing droplet has something to do with creating life for the Albinaurics.",
"Ensha is Sir Gideon Ofnir's silent right-hand man.",
"The nature of Ensha's existence is obscure.",
"Ensha possesses an armor set called the Royal Remains Set.",
"Ensha possesses a weapon called the Clinging Bone.",
"The armor set and weapon seem to suggest that Ensha is the reanimated remains of a king referred to as the Soulless King.",
"From Sir Gideon Ofnir's dialogue, it is speculated that Ensha was tasked with finding both halves of the Haligtree Secret Medallion.",
"Ensha attacks the Tarnished at the Roundtable Hold to take the half of the Haligtree Secret Medallion that they have found.",
"Tanith is the consort to Lord Rykard.",
"Tanith is the adoptive mother of Rya.",
"Tanith worked as a dancer in an unnamed foreign land.",
"Tanith caught Lord Rykard's eye and became his consort.",
"Lord Rykard swore himself to blasphemy.",
"Lord Rykard became one with the God-Devouring Serpent.",
"Even after Lord Rykard's men turned against him, Tanith continued to stay by his side.",
"Tanith was given the Tonic of Forgetfulness as an out.",
"Tanith is now the Lady of the Volcano Manor.",
"Tanith recruits Tarnished who are willing to rise against the Greater Will.",
"Tanith recruits Tarnished to become recusants.",
"Those Tarnished who proved themselves worthy were granted an audience by Lord Rykard.",
"Those Tarnished who were granted an audience by Lord Rykard were devoured.",
"Those Tarnished who were devoured became part of the Volcano Manor family.",
"The Tarnished can first meet Bernahl in Stormhill.",
"Bernahl was said to be a Tarnished worthy of becoming Elden Lord.",
"Bernahl was carrying out his destined path without doubt.",
"Bernahl's maiden threw herself into 'the fire'.",
"There are a few speculations as to what Bernahl's maiden throwing herself into 'the fire' might mean.",
"Some speculate that Bernahl's maiden succumbed to the flame of frenzy.",
"Others speculate that similar to Melina, Bernahl's maiden was thrown into the Forge of the Giants as kindling for burning the Erdtree.",
"The Tarnished can later find Bernahl as a recusant at the Volcano Manor.",
"After defeating Rykard, Bernahl denounces the Greater Will.",
"Bernahl vows to fell the Greater Will on behalf of his brother.",
"Rya's real name is Zorayas.",
"Rya is a Man-Serpent disguised as a human.",
"Rya is the scout for the Volcano Manor.",
"Only the Tarnished knows Rya's true form.",
"Tanith is Rya's adoptive mother.",
"Rya holds great regard for Tanith.",
"Rya strongly believes in Tanith's work.",
"Rya strongly believes in the endeavors of the Volcano Manor.",
"Rya's quest involves finding the truth behind her origins.",
"Tanith told Rya that she was born by the grace of a great king.",
"Rya notices that the Volcano Manor isn't all that it seems.",
"Rya eventually confronts Tanith about the secrets of the manor.",
"Rya confronts Tanith about other secrets Tanith has been keeping from her.",
"The talisman Rya leaves behind at the end of her quest suggests that her mother was Daedicar.",
"Daedicar was a woman who was said to have birthed multiple grotesque children.",
"Daedicar's grotesque children were a result of her committing countless acts of adultery.",
"Patches the Untethered is a bandit.",
"Patches the Untethered tricks unsuspecting people into various death traps.",
"Patches the Untethered tricks unsuspecting people into entrapment schemes.",
"If the Tarnished spares Patches the Untethered, Patches the Untethered will sell the Tarnished various goods.",
"Patches the Untethered presumably obtains the goods from the corpses of those he successfully tricked.",
"Patches the Untethered mentions that his band of bandits comprises foot soldiers.",
"Patches the Untethered mentions that his band of bandits comprises survivors of defeated armies.",
"The survivors of defeated armies were left to fend for themselves.",
"Patches' Emporium can be accessed when reaching Volcano Manor.",
"Patches the Untethered seems to have taken a liking to Tanith.",
"Patches the Untethered endangers himself to obtain the Dancer's Castanets for Tanith.",
"Patches the Untethered hopes that the Dancer's Castanets will put Tanith back to her right mind after Rykard's defeat.",
"Diallos is the youngest son of House Hoslow.",
"Diallos lives in the shadow of his elder brother, Juno Hoslow.",
"Juno Hoslow is a formidable fighter.",
"Diallos was all bark but no bite.",
"Diallos's demeanor is unbefitting for a family whose motto revolves around bloodshed.",
"Despite their differences, Diallos and Juno care for each other very much.",
"Juno uses his position to dote on Diallos.",
"Diallos looks up to Juno as a role model.",
"Jar-Bairn is a young jar living in Jarburg.",
"Jarburg is a secret village of peaceful Living Jars.",
"Jar-Bairn is one of the few living Jars capable of speaking to the Tarnished.",
"Jar-Bairn is a warrior jar.",
"Jar-Bairn is like his uncle Alexander.",
"The Tarnished may find Jar-Bairn talking in his sleep.",
"Jar-Bairn dreams about reuniting with Alexander.",
"Jar-Bairn dreams about telling Alexander that he is a warrior jar too.",
"Jar-Bairn dreams about poachers destroying the Living Pots at Jarburg.",
"Jar-Bairn dreams about later Diallos taking care of him.",
"Living Jar Shards contain traces of magical power.",
"Living Jar Shards fetch a high price.",
"Living Jars are a prize target for poachers.",
"The only known item crafted with Living Jar Shards is the Ironjar Aromatic.",
"The Ironjar Aromatic is a forbidden defense-boosting consumable.",
"The Ironjar Aromatic is created by Depraved Perfumers.",
"Iron Fist Alexander is an older Living Jar.",
"Iron Fist Alexander left his home of Jarburg to seek great battle.",
"Iron Fist Alexander left his home of Jarburg to hone his combat skills.",
"Iron Fist Alexander is a warrior jar.",
"Warrior jars are Living Jars filled with the remains of warriors.",
"According to Iron Fist Alexander, warrior jars are destined to leave their home.",
"According to Iron Fist Alexander, warrior jars are destined to set out on journeys alone.",
"According to Iron Fist Alexander, warrior jars are destined to become great champions.",
"Jar-Bairn is another entity that shares the belief about warrior jars.",
"It seems as though warrior jars are able to absorb the essence of the fallen warriors they consume.",
"By absorbing the essence of fallen warriors, warrior jars can also pick up some of their martial prowess.",
"Blackguard Big Boggart is a Tarnished and former criminal.",
"Blackguard Big Boggart sells boiled prawns and crabs at the Boilprawn Shack.",
"Blackguard Big Boggart later sells boiled prawns and crabs just outside the royal capital.",
"It is possible that Blackguard Big Boggart was previously convicted for thievery.",
"Blackguard Big Boggart stole Rya's necklace when the Tarnished meets Blackguard Big Boggart.",
"Blackguard Big Boggart used to be cellmates with Dung Eater.",
"Blackguard Big Boggart witnessed Dung Eater defile the body of his friend with the Seedbed Curse.",
"Witnessing Dung Eater defile the body of his friend with the Seedbed Curse was the most harrowing experience Blackguard Big Boggart had ever had.",
"Dung Eater is a Tarnished.",
"Dung Eater bears the heart of an Omen.",
"Dung Eater was a merciless killer even before being brought back to the Lands Between.",
"Dung Eater would defile the corpses of those he killed with Seedbed Curses.",
"Dung Eater would curse the souls of those he killed to never be able to return to the Erdtree.",
"Dung Eater's biggest aspiration is to defile and curse everyone in the Lands Between.",
"Dung Eater's biggest aspiration is to curse all future generations.",
"Dung Eater's dream can be realized by aiding him in gestating the Mending Rune of the Fell Curse.",
"Enia is a Finger Reader that the Tarnished encounters at the Roundtable Hold.",
"The finger readers are interpreters for the Two Fingers.",
"The finger readers share the wisdom of the Greater Will to the inhabitants of the Lands Between.",
"The finger readers that the Tarnished encounters, with the exception of Enia, seem to be frantic from the loss of their Two Fingers.",
"Enia is an agent of the Greater Will.",
"Enia is supportive of the Tarnished burning down the Erdtree when her Two Fingers stop communicating with her.",
"Enia claims that before the Tarnished, another had gathered 2 Great Runes.",
"It is speculated that the person who gathered 2 Great Runes is either Bernahl.",
"Bernahl's armor suggests that he was worthy of becoming a Lord.",
"It is also speculated that the person who gathered 2 Great Runes is Vyke.",
"Vyke was said to be the closest who ever got to becoming Elden Lord before he suddenly sought out the Frenzied Flame.",
"Queen Marika, the Eternal is a Numen chosen and brought from her homeland to the Lands Between by the Greater Will.",
"The Greater Will chose Queen Marika to be their vassal.",
"Queen Marika was gifted Maliketh as a Shadow and half-brother.",
"Queen Marika entrusted the Rune of Death to Maliketh when the Golden Order was established.",
"Queen Marika had two consorts during her reign.",
"The first consort of Queen Marika was Godfrey.",
"Queen Marika and Godfrey had three children together.",
"The children of Queen Marika and Godfrey are Godwyn the Golden and the Omen twins, Morgott and Mohg.",
"Queen Marika and her followers waged wars against several factions and gods in the Lands Between.",
"The wars waged by Queen Marika and her followers were on behalf of the Greater Will.",
"The most notable factions and gods that Queen Marika waged wars against include the Storm Lord, the fire giants and their god, the One-Eyed God, the Academy of Raya Lucaria, and the Carian royal family.",
"It is unclear which side instigated the war against the Dragons and the Godskin Apostles and their god, the Gloam-Eyed Queen.",
"The war against the Giants ended in favor of Queen Marika.",
"Queen Marika realized that she would be unable to extinguish the flame at the Forge of the Giants.",
"The flame at the Forge of the Giants is known as the fabled 'flame of ruin' strong enough to burn the Erdtree.",
"Queen Marika cursed the final Fire Giant survivor to protect the forge for all eternity.",
"When the last war was finally over, Queen Marika took the blessing of grace from Godfrey and his warriors.",
"Godfrey and his warriors were turned into Tarnished by Queen Marika.",
"Queen Marika exiled Godfrey and his warriors from the Lands Between.",
"Queen Marika took Radagon to be her second consort.",
"Queen Marika had twins named Miquella and Malenia with Radagon.",
"At some point, Queen Marika started to harbor doubts towards the Greater Will and the Golden Order.",
"It is speculated that Queen Marika had a hand in the Night of the Black Knives due to her rumored connection with the Black Knife Assassins.",
"Queen Marika's final act of rebellion against the Greater Will was the shattering of the Elden Ring.",
"The shattering of the Elden Ring caused Queen Marika's imprisonment within the Erdtree.",
"The shattering of the Elden Ring also caused the war between the demigods.",
"Radagon of the Golden Order is characterized by his flowing red locks.",
"Radagon is Queen Marika's second chosen consort.",
"Radagon is a great warrior.",
"Radagon's early life and how he came to be a prominent figure in the Golden Order remain a mystery.",
"There is speculation that Radagon may be a smaller-sized Fire Giant.",
"The speculation about Radagon being a smaller-sized Fire Giant comes from the descriptions of the Sword of Milos and Giant's Red Braid.",
"Another running theory is that Radagon was cursed to have red hair by the Fire Giants.",
"The curse of red hair on Radagon is a result of the Golden Order's war with the Fire Giants.",
"Radagon was said to have hated the red-tint of his hair.",
"In the war against Liurnia of the Lakes and its inhabitants, Marika tasked Radagon to lead the Erdtree's armies.",
"The sword monuments that the Tarnished can find in Liurnia suggest that there were two Liurnian Wars.",
"It was after the second war that Radagon and Rennala fell in love.",
"Radagon sought absolution at the Church of Vows using Celestial Dew.",
"Radagon and Rennala were bonded by marriage.",
"The marriage of Radagon and Rennala united the Capital of Leyndell and the Academy of Raya Lucaria.",
"The Glintstone Kris is one of the symbols of the unity of the Capital of Leyndell and the Academy of Raya Lucaria.",
"As is tradition, Rennala bestowed a Moon Greatsword onto Radagon.",
"Rennala and Radagon bore three children.",
"The three children of Rennala and Radagon are General Radahn, Praetor Rykard, and Lunar Princess Ranni.",
"Radagon gifted Rennala an Amber Egg.",
"Radagon left Rennala to join Marika's side when Godfrey and his fellow Tarnished were exiled from the Lands Between.",
"Radagon and Marika had twin demigods named Miquella and Malenia.",
"Radagon reforged his Moon Greatsword into the Golden Order Greatsword.",
"A speculated explanation for the requirement of both Faith and Intelligence in casting Golden Order Incantations is due to Radagon having learned sorceries while Rennala's consort.",
"Radagon learned incantations when he was consort to Queen Marika.",
"A statue in the Royal Capital reveals that Marika and Radagon are one and the same.",
"It is unclear whether Marika and Radagon were always one.",
"It is unclear whether Radagon is a fragment of Marika.",
"Melina's dialogue suggests that Marika and Radagon became one after becoming consorts.",
"Despite being one and the same person, Marika and Radagon held different wills.",
"When Marika shattered the Elden Ring, Radagon used the same hammer she used to try to repair it.",
"Godfrey was the first consort to Queen Marika.",
"Godfrey was the first Elden Lord.",
"Godfrey and Queen Marika had 3 children together.",
"The children of Godfrey and Queen Marika were Godwyn the Golden and the Omen twins, Morgott and Mohg.",
"Godfrey was originally known as Hoarah Loux.",
"Hoarah Loux was a fierce warrior.",
"Hoarah Loux had a strong bloodlust.",
"Hoarah Loux was the chieftain of the badlands.",
"Upon being selected as Queen Marika's first consort, Godfrey took Beast Regent Serosh upon his back.",
"Godfrey took Beast Regent Serosh upon his back to quell his insatiable bloodlust.",
"Godfrey took Beast Regent Serosh upon his back to be more befitting of a Lord.",
"When the Golden Order was established, Godfrey was tasked with leading several wars.",
"Godfrey was tasked with leading wars to further the influence of the Golden Order.",
"One of the wars Godfrey led was against the Giants.",
"Godfrey faced the Storm Lord alone.",
"During Godfrey's reign, gladiatorial combat in colosseums all over the Lands Between was commonplace.",
"The gladiatorial combat in colosseums was held as rituals to honor the Erdtree.",
"The practice of gladiatorial combat died out when Radagon became Queen Marika's next consort.",
"After Godfrey won his last campaign, there were no worthy opponents left to battle with.",
"Marika took away the Erdtree's blessing from Godfrey and countless others.",
"Godfrey and countless others were turned into Tarnished.",
"Godfrey led the Tarnished out of the Lands Between in a journey referred to as the Long March.",
"Godfrey's axe was broken in a battle during the Long March.",
"After the Long March ended, Godfrey reverted back to becoming a simple warrior.",
"Godfrey still carried Serosh on his back after reverting back to a simple warrior.",
"Rennala is the Queen of the full moon.",
"Rennala was a young astrologer.",
"Rennala would always gaze up at the stars.",
"Rennala had a chance encounter with the Full Moon.",
"Rennala learnt of the magic of the Full Moon.",
"Rennala became one of the most powerful glintstone sorcerers.",
"Rennala's new mastery over lunar magic bewitched the Academy of Raya Lucaria.",
"Rennala became head of the Academy of Raya Lucaria.",
"Rennala became head of the Glintstone Knights.",
"Rennala established the Carian family as royalty.",
"During the Second Liurnian War, the Golden Order waged territorial war against the Academy.",
"Rennala met one of the Erdtree's champions, Radagon.",
"Rennala fought against Radagon.",
"Rennala and Radagon fell in love.",
"Rennala and Radagon reconciled at the Church of Vows.",
"Rennala bestowed upon Radagon a Moon Greatsword.",
"The Moon Greatsword was later reforged into the Golden Order Greatsword.",
"Rennala and Radagon's union bore three children.",
"The children of Rennala and Radagon are Lunar Princess Ranni, General Radahn, and Praetor Rykard.",
"One night, Rennala took Ranni out stargazing.",
"Rennala took Ranni out stargazing as she did in her childhood.",
"Ranni met her own moon, the Dark Moon, during the stargazing.",
"Godfrey was exiled from the Lands Between.",
"Radagon returned to Marika's side.",
"Rennala was devastated by Radagon's return to Marika's side.",
"Rennala grew weak after Radagon's return to Marika's side.",
"Rennala's charm over the Academy fell.",
"The scholars of the Academy rebelled against the Carian royal family.",
"The Cuckoo Knights launched an attack against Caria Manor.",
"Rennala ended up being locked up in the Grand Library.",
"The Tarnished finds Rennala cradling the Amber Egg.",
"The Amber Egg was given to Rennala by Radagon as a parting gift.",
"Morgott is one of two Omen twins born of Queen Marika.",
"Morgott is one of two Omen twins born of Godfrey.",
"The horns of an Omen were signifiers of the divine in the ages before the Erdtree.",
"After the establishment of the Golden Order, Omen were thought to be cursed beings without the guidance of grace.",
"Omen had their horns cut off.",
"Omen were subject to slavery.",
"Those Omen born with royal blood were hidden from the world.",
"Those Omen born with royal blood were shackled deep underneath Leyndell in the Subterranean Shunning-Grounds.",
"Despite being locked away and shunned, Morgott still loved the Order.",
"During the Shattering, Leyndell was leaderless and defenseless.",
"Morgott knew that Leyndell wouldn't accept an Omen as a leader.",
"Morgott ruled the capital in the shadows as the Unveiled Monarch.",
"During the Second Defense of Leyndell, Morgott successfully defended the capital from invading demigods.",
"During the Second Defense of Leyndell, Morgott successfully defended the Erdtree from invading demigods.",
"Morgott's dialogue suggests he attempted to claim the throne of the Elden Lord.",
"The Erdtree warded Morgott off from claiming the throne of the Elden Lord.",
"The Tarnished will first encounter Morgott under the pseudonym, Margit.",
"Morgott, under the pseudonym Margit, prevents the Tarnished from challenging Godrick in Stormveil Castle.",
"Morgott, under the pseudonym Margit, prevents the Tarnished from obtaining one of many Great Runes required to enter the capital.",
"Mohg is known as the Lord of Blood.",
"Mohg is the son of Queen Marika.",
"Mohg is the son of Godfrey, who is Queen Marika's first consort.",
"Mohg has a twin brother.",
"Mohg fully embraced his accursed Omen blood and traits.",
"Mohg's twin brother distanced himself from his Omen nature.",
"Mohg was shackled deep within the Subterranean Shunning-Grounds.",
"Mohg encountered the Formless Mother while imprisoned underground.",
"The Formless Mother is an outer god like the Greater Will.",
"The encounter with the Formless Mother caused Mohg's accursed omen blood to ignite.",
"The ignition of Mohg's accursed omen blood gave him the ability to cast bloodflame incantations.",
"Mohg used his spear, known as Mohgwyn's Sacred Spear, to further communicate with the Formless Mother.",
"At some point, Mohg managed to escape from the Subterranean Shunning-Grounds.",
"Mohg established the Mohgwyn Palace in a secluded part of the Siofra River.",
"Mohg recruited multiple people to become followers of the upcoming Mohgwyn Dynasty.",
"Mohg offered deals to some followers, such as Bloody Finger Okina.",
"Mohg kidnapped others, such as the War Surgeons.",
"Mohg is not an Empyrean himself.",
"Mohg is unable to ascend to godhood.",
"Mohg hoped to claim the title of monarch by raising empyrean Miquella to full godhood.",
"Mohg aimed to become the consort of empyrean Miquella.",
"Mohg stole the slumbering Miquella from inside the Haligtree.",
"Mohg attempted to rouse Miquella with his accursed blood.",
"Miquella never woke from his slumber, despite Mohg's offerings of blood.",
"Miquella never woke from his slumber, despite Mohg sharing his bedchambers with him.",
"Rykard is known as the lord of blasphemy.",
"Praetor Rykard is the Lord of the Volcano Manor.",
"Praetor Rykard is a ruthless justiciar.",
"Rykard is the son of Rennala and Radagon.",
"Rykard became a demigod after Radagon's unity with Queen Marika.",
"Rykard presides over Mt. Gelmir.",
"Rykard was served by the Gelmir Knights.",
"The lava sorceries that the Tarnished can learn were created by Rykard.",
"Some of the lava sorceries are old hexes from Mt. Gelmir that Rykard turned into practical sorceries.",
"At some point, Rykard met Tanith in a foreign land.",
"Rykard brought Tanith back to the Lands Between to be his consort.",
"Rykard had a hand in the Night of the Black Knives.",
"The extent of Rykard's involvement in the Night of the Black Knives is unclear.",
"The Blasphemous Claw was an item rewarded by Rykard's sister Ranni.",
"The Blasphemous Claw allowed Rykard to challenge Maliketh as a last resort.",
"The description for the Taker's Cameo implies that Rykard believed that Marika and her Order ruled by force.",
"Rykard swore himself to blasphemy.",
"Rykard sought to overthrow Marika and her Order.",
"Rykard's ambition drew many towards him.",
"The ancient people of Mt. Gelmir worshipped a powerful serpent god.",
"The ancient people of Mt. Gelmir offered sacrifices to the powerful serpent god.",
"Rykard encountered the God-Devouring Serpent.",
"Rykard offered himself and his Great Rune as sacrifices to the God-Devouring Serpent.",
"Rykard's sacrifices granted him immortality.",
"Rykard's immortality allowed him to grow and devour people and gods alike for all eternity.",
"Rykard's fall into greed and glutinous depravity caused most of his followers to turn against him.",
"Tanith was a notable exception among Rykard's followers.",
"Those who were once Gelmir Knights sought out the Serpent-Hunter.",
"The Serpent-Hunter is a great spear designed to hunt the immortal serpent.",
"The Gelmir Knights sought to put an end to their Lord, Rykard.",
"The Gelmir Knights found the mythical weapon, the Serpent-Hunter.",
"The Gelmir Knights were unsuccessful in defeating Rykard.",
"The evidence of the Gelmir Knights' failure is shown by the corpses holding the Serpent-Hunter in Rykard's boss room.",
"When the Tarnished visits the Volcano Manor, they can find its members following Rykard's blasphemous path.",
"It is later revealed that those who proved themselves as recusants were granted an audience with Rykard.",
"Those who proved themselves as recusants became part of Rykard's family by being devoured by the great serpent himself.",
"Covenants are replaced by Accords or informal NPC Factions in Elden Ring.",
"Players can select allegiances or pledges undertaken to specific deities or groups of NPCs.",
"The traditional sense of Dark Souls Covenants is not present in the Lands Between.",
"There are groups of NPCs around the world that players can choose to aid.",
"Aiding groups of NPCs slowly raises players' rewards and bonds with these NPCs.",
"Miyazaki confirmed that traditional Covenants were not going to be in Elden Ring.",
"Miyazaki aimed to make PvP more accessible in Elden Ring.",
"Traditional Covenants would be replaced with the Summoning Pools and various fingers.",
"There are no Covenants in Elden Ring.",
"Multiplayer paths are open without the need to ally with a specific faction.",
"Faction allegiance or personal Accords still exist in Elden Ring.",
"Players can obtain special items with faction allegiance or personal Accords.",
"Players can progress Side Quests with faction allegiance or personal Accords.",
"The Volcano Manor faction houses a group of Recusant Tarnished.",
"The group of Recusant Tarnished is led by Praetor Rykard.",
"Those in the Volcano Manor faction seek to rebel against the Erdtree.",
"A newly recruited Tarnished must first invade their fellow Tarnished to prove their resolve before being granted an audience with their Lord.",
"The Volcano Manor is a side faction located in Mt Gelmir.",
"The Volcano Manor is surrounded by biting lava ponds.",
"Within the location of Volcano Manor, Tanith can be found.",
"Tanith will welcome new recruits into their side of battle.",
"The Volcano Manor offers a quest line to prove that a recruit's service is applicable.",
"Upon joining the Volcano Manor faction, a new recruit will have access to the Recusant Finger.",
"The Recusant Finger is an infinite-use invasion item.",
"The Recusant Finger dubs the user as a Recusant to the host.",
"Completing the Volcano Manor questline nets various equipment and spells as a reward.",
"Completing the questlines of the Volcano Manor NPCs nets various equipment and spells as a reward.",
"Joining the Volcano Manor faction requires invading and defeating fellow Tarnished.",
"Joining the Volcano Manor faction has no consequence in the bonds with any other faction or NPC.",
"Tanith is a member of this faction.",
"Patches is a member of this faction.",
"Rya is a member of this faction.",
"Bernahl is a member of this faction.",
"One possible reward from joining this faction is the Bull-Goat Set.",
"One possible reward from joining this faction is Crepus's Vial.",
"One possible reward from joining this faction is Daedicar's Woe.",
"One possible reward from joining this faction is Gelmir's Fury.",
"One possible reward from joining this faction is Hoslow's Petal Whip.",
"One possible reward from joining this faction is Hoslow's Set.",
"One possible reward from joining this faction is Magma Shot.",
"One possible reward from joining this faction is Magma Whip Candlestick.",
"One possible reward from joining this faction is the Raging Wolf Set.",
"One possible reward from joining this faction is the Recusant Finger.",
"One possible reward from joining this faction is the Serpentbone Blade.",
"One possible reward from joining this faction is the Scaled Set.",
"One possible reward from joining this faction is Taker's Cameo.",
"The Mohgwyn Dynasty is a faction led by Mohg, Lord of Blood.",
"The Mohgwyn Dynasty is similar to the Volcano Manor.",
"Those in service to the Mohgwyn Dynasty faction invade other Tarnished.",
"Those in service to the Mohgwyn Dynasty faction renounce the Greater Will.",
"Bloodshed is the only motive for invasion in the Mohgwyn Dynasty faction.",
"The beginnings of the Mohgwyn Dynasty can be found in Mohgwyn Palace.",
"The Mohgwyn Dynasty is another invasion-centered faction.",
"The Mohgwyn Dynasty is spearheaded by Mohg, Lord of Blood.",
"The Lord of Blood himself can be found in Mohgwyn Palace.",
"Mohgwyn Palace is located deep underground by the Siofra River.",
"Not much is revealed about Mohg or his dynasty.",
"Bloodshed is a key element of the Mohgwyn Dynasty.",
"Recanting the wisdom of the Two Fingers is a key element of the Mohgwyn Dynasty.",
"Progressing enough through Varre's quest grants a Bloody Finger.",
"The Bloody Finger is an infinite-use invasion item.",
"The Bloody Finger dubs the user as a Bloody Finger to the host.",
"Joining the Mohgwyn Dynasty faction and completing the relevant questlines has no consequence on other NPC/faction attitudes towards the player.",
"Mohg is a character in this faction.",
"Mohg holds the title of Lord of Blood.",
"White Mask Varre is a character in this faction.",
"One possible reward from joining this faction is the Bloody Finger.",
"Another possible reward from joining this faction is the Festering Bloody Finger.",
"Another possible reward from joining this faction is the Pureblood Knight's Medal.",
"Another possible reward from joining this faction is Varre's Bouquet.",
"The remaining members of the Carian Royal Family are Rennala, Ranni, and their trusted advisors.",
"Rennala once held power over the Academy of Raya Lucaria.",
"Rennala's grief over Radagon's departure caused her to weaken.",
"The scholars of the Academy of Raya Lucaria rebelled against Rennala.",
"Serving the Carian Royal Family means serving Ranni, the last Carian princess.",
"Ranni is on a mission to usurp the Two Fingers and Greater Will.",
"Ranni is rebelling against her fate as an Empyrean.",
"Rennala is the Queen of the Full Moon.",
"Rennala resides in the Academy of Raya Lucaria.",
"Ranni is the Lunar Princess.",
"Ranni has trusted advisors.",
"To join Ranni's faction, one must visit Ranni at her tower in the Three Sisters.",
"Accepting Ranni's accord allows one to join her faction.",
"Accepting Ranni's accord is similar to the experience at the Volcano Manor.",
"Accepting Ranni's accord will lead one to go against the Greater Will.",
"Accepting Ranni's accord aids Ranni in her journey on the 'dark path'.",
"Ranni's journey on the 'dark path' is to fight against her destiny as an Empyrean.",
"Progressing through and completing Ranni's quest gives access to the 'Age of the Stars' Ending.",
"Completing Ranni's quest provides access to a secret area in the Carian Study Hall.",
"Joining Ranni's faction will not affect one's standing with other NPCs.",
"Completing Seluvis' quest all the way through will cause Ranni to deeply distrust the player.",
"If Ranni deeply distrusts the player, she will disappear along with the other members of her group.",
"Blaidd is an NPC in this faction.",
"Preceptor Seluvis is an NPC in this faction.",
"Ranni the Witch is an NPC in this faction.",
"Rennala is the Queen of the Full Moon and an NPC in this faction.",
"War Counsellor Iji is an NPC in this faction.",
"One possible reward from joining this faction is the Carian Inverted Statue.",
"One possible reward from joining this faction is the Dark Moon Greatsword.",
"One possible reward from joining this faction is the Dark Moon Ring.",
"One possible reward from joining this faction is the Discarded Palace Key.",
"One possible reward from joining this faction is the Magic Scorpion Charm.",
"Those Who Live in Death refer to the numerous undead plaguing the Lands Between.",
"The existence of Those Who Live in Death defies the tenets of the prevalent Golden Order.",
"Those Who Live in Death live in persecution.",
"Those in the faction of Those Who Live in Death are empathetic towards Those Who Live in Death.",
"Those in the faction of Those Who Live in Death join in awaiting the rise of their Lord.",
"The Lord referred to is Godwyn, Prince of Death.",
"Godwyn is the first of the dead demigods.",
"The undead that plague the Lands Between go by the title, Those Who Live in Death.",
"The existence of Those Who Live in Death goes against the principle of immortality brought by the Golden Order.",
"Fia is the one who considers herself the mother of Those Who Live in Death.",
"Fia is known as the Deathbed Companion.",
"Fia can be found at the Roundtable Hold.",
"Fia can later be found by the side of her companion in Deeproot Depths.",
"Fia has a quest to gain access to the 'Age of the Duskborn' Ending.",
"Fia's quest unlocks a secret boss fight.",
"There is no consequence to any other NPC or faction bond when joining the faction of Those Who Live in Death.",
"Fia is an NPC in this faction.",
"Godwyn is an NPC in this faction.",
"Godwyn holds the title of Prince of Death.",
"One possible reward from joining this faction is Fia's Mist.",
"Another possible reward from joining this faction is the Mending Rune of the Death-Prince.",
"Another possible reward from joining this faction is Radiant Baldachin's Blessing.",
"Another possible reward from joining this faction is the Remembrance of the Lichdragon.",
"The Golden Order Faction was established by Queen Marika.",
"Queen Marika was brought to the Lands Between by the Greater Will.",
"The Golden Order Faction is the most dominant faction in the Lands Between.",
"The tenets of the Golden Order govern the rules and status quo to be practiced by its followers.",
"Many followers of the Golden Order follow its tenets blindly.",
"After the Shattering, a few members of the Golden Order are starting to question the infallibility of the Order.",
"Few people left in the Lands Between stay devout followers of the Golden Order.",
"Some remaining followers of the Golden Order are scholars seeking to preserve its teachings and history in writing.",
"Brother Corhyn is a scholar seeking to preserve the teachings and history of the Golden Order.",
"Goldmask is a scholar seeking to preserve the teachings and history of the Golden Order.",
"Some remaining followers of the Golden Order are stalwart protectors against the undead.",
"D, Hunter of the Dead, is a stalwart protector against the undead.",
"Melina does not align herself with any faction in particular.",
"Melina's accord and request to mend the Elden Ring seem to align with the views of the Golden Order.",
"Following Brother Corhyn and Goldmask's quest to the end allows access to the 'Age of Order' Ending.",
"Following Brother Corhyn and Goldmask's quest to the end unlocks the secrets behind Radagon and Marika.",
"There is no consequence to joining the Golden Order Faction.",
"There are no factions that cause any consequence to the Golden Order Faction.",
"Brother Corhyn is an NPC in this faction.",
"D is an NPC in this faction.",
"D is known as Hunter of the Dead.",
"D's Twin Brother is an NPC in this faction.",
"Enia is an NPC in this faction.",
"Gideon Ofnir is an NPC in this faction.",
"Goldmask is an NPC in this faction.",
"Kenneth Haight is an NPC in this faction.",
"Miriel is an NPC in this faction.",
"Miriel is known as Pastor of Vows.",
"Corhyn's Robe is a reward.",
"Goldmask's Set is a reward.",
"Inseparable Sword is a reward.",
"Mending Rune of Perfect Order is a reward.",
"Twinned Set is a reward.",
"Frenzied Flame is a covert faction.",
"The covert faction is led by the Three Fingers.",
"The Three Fingers are similar to the Two Fingers.",
"The Three Fingers are vassals for a different unknown Outer God.",
"The unknown Outer God rejects the Greater Will.",
"The unknown Outer God proclaims that all that is wrong with the Lands Between is due to the mistakes of the Greater Will.",
"Those in the Frenzied Flame faction await one who would take up the mantle of Lord of Chaos.",
"The Lord of Chaos is expected to burn the world down and melt all of its troubles away.",
"The Greater Will is only one of the outer gods who have influence over the Lands Between.",
"Under the guidance of the Three Fingers and their finger maiden, players will be able to come into contact with another of the mysterious outer gods.",
"The other mysterious outer god seems to reject the Greater Will.",
"It is implied from the description of the Nomadic Merchant's Set that the Nomadic Merchants were the first to summon the flame of frenzy into the Lands Between.",
"Players must find the Three Fingers in the Frenzied Flame Proscription to unlock the 'Lord of Frenzied Flame' Ending.",
"Unlocking the 'Lord of Frenzied Flame' Ending locks players out of getting any other ending.",
"Unlocking the 'Lord of Frenzied Flame' Ending does not hinder progress towards completing any NPC quest.",
"Players do not require finishing any quest to acquire the 'Lord of Frenzied Flame' Ending.",
"Aiding Hyetta gives more insight towards the Frenzied Flame faction.",
"Hyetta is an NPC in this faction.",
"Nomadic Merchants are NPCs in this faction.",
"Three Fingers is an NPC in this faction.",
"Shabriri is an NPC in this faction.",
"Of all the schools of magic, scholarly endeavors on the Primeval Current are forbidden in the Academy of Raya Lucaria.",
"Those who engage in scholarly endeavors on the Primeval Current are punished by transforming into a ball-like form.",
"Few scholars insist on learning the secrets of the Primeval Current despite the threat of punishment.",
"The Sorceress Sellen is one of the few scholars who insist on learning the secrets of the Primeval Current.",
"You will not be studying about the Primeval Current.",
"You can aid Sellen in her studies by doing her quest.",
"There aren't any consequences in aiding Sellen.",
"At the end of Sellen's quest, you will have to make a choice.",
"The choice is between invading Sellen with Witch Hunter Jerren or being summoned to help Sellen against Witch Hunter Jerren.",
"Your choice will affect which rewards you are able to receive.",
"Master Lusat is an NPC in this faction.",
"Primeval Sorcerer Azur is an NPC in this faction.",
"The School of Graven Mages is an NPC in this faction.",
"Sorceress Sellen is an NPC in this faction.",
"One possible reward from joining this faction is Azur's Glintstone Set.",
"One possible reward from joining this faction is Eccentric Set.",
"One possible reward from joining this faction is Glintstone Kris.",
"One possible reward from joining this faction is Lusat's Set.",
"One possible reward from joining this faction is Shard Spiral.",
"One possible reward from joining this faction is Witch's Glintstone Crown.",
"Other Factions is a list of factions not joinable by the player character.",
"Other Factions consists of several enemies in the game.",
"Godskin Apostles is the name of a group of people that served an entity known as the Dusk-Eyed Queen or Gloam-Eyed Queen.",
"The only thing known about the Dusk-Eyed Queen is that she was an Empyrean.",
"The god-slaying black flame wielded by the Dusk-Eyed Queen was fueled by Destined Death.",
"The Dusk-Eyed Queen was bested by Maliketh, the Black Blade.",
"The god-slaying black flame wielded by the Dusk-Eyed Queen was locked away after her defeat.",
"Black Knife Assassins is a group of assassins responsible for the death of Godwyn the Golden.",
"The death of Godwyn the Golden occurred during the historical event known as the Night of the Black Knives.",
"Alecto is the ringleader of the Black Knife Assassins.",
"The player character can find Alecto in-game.",
"The player character does not find the reason the Black Knife Assassins carried out the assassination.",
"Radahn's Faction refers to the loyal knights surrounding General Radahn during the Shattering.",
"Those who fought at General Radahn's side are referred to as Redmane Knights or Radahn Soldiers.",
"Malenia's Faction consists of many soldiers and servants that remain loyal to Malenia after her battle against Radahn.",
"The soldiers and servants loyal to Malenia are the Kindreds of Rot and the Cleanrot Knights.",
"The player character can help Gowry and Millicent during their quests.",
"The player character does not join Malenia's faction while helping Gowry and Millicent.",
"Miquella's Faction has limited information known about Miquella's rule and his followers.",
"The Haligtree Soldiers found in the Haligtree are waiting for their lord to return.",
"The land of the Haligtree was created by Miquella.",
"The land of the Haligtree is said to be the promised land of the Albinaurics."]