eldenring_propositions = ['Lore in Elden Ring covers all the information related to the world of Elden Ring.',
 'Lore in Elden Ring covers all the information related to the mythos of Elden Ring.',
 'Lore in Elden Ring includes past events that occurred long ago.',
 'Lore in Elden Ring includes the history of the Lands Between.',
 'Lore in Elden Ring includes the mystery of the elusive Elden Ring.',
 'All information related to the world and mythos of Elden Ring can be found on this page.',
 'This page contains heavy spoilers.',
 'The Mythos of Elden Ring was written by George R. R. Martin.',
 'The Shattering is a devastating war between the children of Marika.',
 'The children of Marika are Demigods of the Lands Between.',
 "After Godwyn the Golden's death, the Elden Ring was somehow shattered.",
 'The power of a Great Rune fueled the conflict.',
 'The battle of General Radahn against Malenia the Severed illustrated that neither strength nor skill alone would be enough to take control of the entirety of the lands Marika had united.',
 'The Shattering was initiated by the demigods’ hunger for power.',
 'The Lands Between is the world of Elden Ring.',
 'Those who live in The Lands Between were blessed by Grace through the Elden Ring.',
 'Those who live in The Lands Between were blessed by Grace through the Erdtree.',
 'Those who were blessed by the Elden Ring are characterized by having a golden aura that can be seen in their eyes.',
 'At some point, some of those who were blessed lost their grace.',
 'Those who lost their grace were exiled and labeled the Tarnished.',
 'At some point in time, the Elden Ring was shattered.',
 'The shards of the Elden Ring were scattered across the Lands Between.',
 'The largest pieces of the Elden Ring were called Great Runes.',
 'The Great Runes were claimed by the six Demigod children of Queen Marika the Eternal.',
 'The six Demigod children of Queen Marika the Eternal inherited different powers.',
 'The six Demigod children of Queen Marika the Eternal were physically changed and twisted due to being corrupted by the power of the Great Runes.',
 'The Lands Between is divided into seven distinct areas.',
 'Limgrave is an area.',
 'Elden Ring is a video game.',
 'Hidetaka Miyazaki is a game director.',
 'Melina is one of the first people the Tarnished encounters on their journey.',
 'Melina maintains an air of mystery throughout the game.',
 'Melina does not have a physical form.',
 "Melina acts as the Tarnished's Finger Maiden in exchange for taking Melina to the Erdtree.",
 'Later on, Melina asks the Tarnished to take her to the Mountaintops of the Giants.',
 'Melina approaches the Tarnished to aid her in her search for her purpose.',
 'Melina believes that her purpose was given to her by her mother.',
 'Melina believes that her mother can be found at the base of the Erdtree.',
 "Many people speculate that Melina's mother is Marika.",
 'When summoned, Melina wields the Blade of Calling.',
 'The Blade of Calling is a dagger that was previously owned by the kindling maiden.',
 "Melina's role as kindling is fitting when the Erdtree is burnt down.",
 "Speaking with Melina at various Sites of Grace reveals her ability to recall echoes of Queen Marika's past actions and words.",
 "Melina offers echoes of Queen Marika's past actions and words in lieu of a 'maiden's guidance'.",
 'Melina holds contempt for the Frenzied Flame.',
 'Melina believes that whoever lords over the chaos and damage brought by the Frenzied Flame is no Lord at all.',
 'If the Tarnished takes the Frenzied Flame before the event at the Forge of the Giants, Melina will leave the Tarnished.',
 'Melina will threaten to deliver the Tarnished Destined Death once they become Lord of the Frenzied Flame.',
 'The White Masks encountered in Mohgwyn Palace were initially abducted by Mogh.',
 'Mogh was the Lord of Blood.',
 'The White Masks were turned into Bloody Fingers through an unknown ritual.',
 "The unknown ritual involved Mogh's accursed Omen blood.",
 'Of the four White Masks encountered in the game, Varre was able to withstand and tame the accursed blood.',
 'Varre remains loyal to the Mohgwyn Dynasty despite being abducted by the Lord of Blood.',
 'Varre tries to indoctrinate the Tarnished into the Mohgwyn Dynasty.',
 'Varre calls out to Mohg at the end of his questline.',
 'Varre blesses the Mohgwyn Dynasty even as he is dying.',
 'Varre was forsaken by his Lord.',
 'Yura is a samurai from the Land of Reeds.',
 "Yura's purpose is to hunt down Bloody Fingers.",
 "Yura's biggest target is Eleonora.",
 'Yura warns the Tarnished against the dangers of Dragon Communion.',
 'Yura states that those who partake in Dragon Communion one day lose their humanity.',
 'Other Bloody Fingers that the Tarnished encounter are targets of Yura.',
 'Sorcerer Rogier is a Tarnished.',
 'Sorcerer Rogier has an easy-going nature.',
 'Sorcerer Rogier is said to be a wise and powerful sorcerer by his old travelling companion, D.',
 'Sorcerer Rogier was once a scholar.',
 'Sorcerer Rogier was seeking the truth behind the Night of the Black Knives.',
 "Sorcerer Rogier's scholarly pursuits eventually brought him under Stormveil Castle.",
 'Sorcerer Rogier found and disturbed a corpse under Stormveil Castle.',
 'Disturbing the corpse caused Sorcerer Rogier to be afflicted with Death.',
 'D sees Those Who Live in Death as a threat against the Golden Order.',
 'Sorcerer Rogier is empathetic towards Those Who Live in Death.',
 'Sorcerer Rogier believes Those Who Live in Death have committed no offence.',
 "By finishing Sorcerer Rogier's quest, the Tarnished is able to help Sorcerer Rogier reveal many insights about the night of the assassination.",
 'Sorcerer Rogier finally succumbs to his affliction.',
 'Fia is a Tarnished Deathbed Companion.',
 'Fia was driven from her home when awoken by the guidance of grace.',
 'Fia describes a Deathbed Companion as a person who receives warmth and life from numerous champions.',
 'A Deathbed Companion lays with the remains of an exalted noble to revive them.',
 "The act of laying with the remains of an exalted noble is revered in Fia's homeland.",
 'Fia is empathetic towards Those Who Live in Death.',
 'Fia has put it upon herself to be the guardian of Those Who Live in Death.',
 "Before meeting Fia at Deeproot Depths, the Tarnished will encounter Fia's champions.",
 "One of Fia's champions is Rogier.",
 "Another of Fia's champions is Lionel the Lionhearted.",
 'Lionel the Lionhearted is a knight Fia met on her journey to the Lands Between.',
 "Lionel the Lionhearted declared himself to be Fia's father.",
 "Fia implies that bringing together Ranni's half of the Cursemark of Death from the Divine Tower of Liurnia and Godwyn's half from D is significant.",
 "Fia implies that being Godwyn's Deathbed Companion will result in Godwyn being reborn as a rune.",
 'The rune representing Those Who Live in Death is called the Mending Rune of the Death-Prince.',
 'D is a devout follower of the Golden Order.',
 'D hunts Those Who Live in Death.',
 'D notably hunts Tibia Mariners for their Deathroot.',
 'D has a twin brother.',
 "D's twin brother's name is suggested to be Darian.",
 'D and Darian have separate bodies and separate minds.',
 'D and Darian share the same soul.',
 'One twin cannot be conscious when the other is conscious.',
 'Other Orders would have seen D and Darian as cursed beings.',
 'The two twins found comfort in the Golden Order.',
 'The Golden Order is the one Order that does not see D and Darian as cursed beings.',
 'D states that Those Who Live in Death go against the principles of the Golden Order.',
 'D states that Those Who Live in Death must be exterminated.',
 'D is known as the Beholder of Death.',
 'D has a twin brother.',
 "The name of D's twin brother is inferred to be Devin from D's voicelines.",
 'Devin can be found slumbering in the Siofra Aqueduct while D is alive.',
 'Devin can be found grieving in the Siofra Aqueduct when D is dead.',
 'Devin is unable to talk and interact with D.',
 'Despite not being able to talk and interact, D and Devin seem to be close.',
 "Devin swears revenge against D's killer.",
 "D's killer may be Fia or the Tarnished.",
 "Devin swears revenge when given D's armor set.",
 'Gurranq is a large beastman who hungers for Deathroot.',
 'Roderika is a Tarnished who was driven away from her home across the sea.',
 'The cloak that Roderika wears implies that Roderika used to be a member of royalty.',
 'At some point upon arriving at the Lands Between, Roderika happened upon White Mask Varre.',
 'White Mask Varre gave Roderika the same advice as he gives the Tarnished at the beginning of their journey.',
 'White Mask Varre advised Roderika to seek Godrick and his Great Rune at Stormveil Castle.',
 'Upon arriving at Stormhill, the men escorting Roderika were taken and sacrificed for grafting.',
 'Roderika feels guilt about the fact that she is too afraid to join the men who were sacrificed.',
 "Roderika moves to the Roundtable Hold to find purpose after receiving the hopeful echoes of her men through the Chrysalids' Memento.",
 "Smithing Master Hewg recognises Roderika's potential for spirit tuning through Roderika's eyes.",
 'With a bit of encouragement from the Tarnished, Smithing Master Hewg trains Roderika to be a skillful spirit tuner.',
 'Roderika and Smithing Master Hewg become close.',
 'Even as the Roundtable Hold is burning down, Roderika stays behind with Smithing Master Hewg to repay his kindness.',
 'Smithing Master Hewg is a misbegotten chained and imprisoned at the Roundtable Hold.',
 'Smithing Master Hewg is tasked by Queen Marika to smith a weapon strong enough to kill a god.',
 'Smithing Master Hewg makes the task of smithing a weapon strong enough to kill a god his life goal.',
 'Smithing Master Hewg strongly believes that the Tarnished will be the one to become Elden Lord.',
 'Smithing Master Hewg will say that the Tarnished will be the one to become Elden Lord before he completely loses his memory.',
 'Nepheli Loux is the adoptive daughter of Sir Gideon Ofnir.',
 'Sir Gideon Ofnir took Nepheli Loux in when Nepheli Loux lost the guidance of grace.',
 'Nepheli Loux became a Tarnished.',
 'Nepheli Loux is a skilled warrior.',
 'Nepheli Loux believes in standing up and enacting justice for the weak and oppressed.',
 'Nepheli Loux once believed that Sir Gideon Ofnir held the same beliefs.',
 'Nepheli Loux learned that Sir Gideon Ofnir was the mastermind behind the attack on the Village of the Albinaurics.',
 'After learning this information, Nepheli Loux loses faith in Sir Gideon Ofnir.',
 'It is speculated that Nepheli Loux has ties with the first Elden Lord, Godfrey.',
 'Nepheli Loux has ties with the Golden Lineage.',
 'Nepheli Loux bears the same last name as Hoarah Loux.',
 'Kenneth Haight deems Nepheli Loux worthy of taking up the mantle of leader of Limgrave.',
 'Kenneth Haight is a member of the Erdtree royalty.',
 'Kenneth Haight is a self-proclaimed rightful leader of Limgrave.',
 'Kenneth Haight is the owner of Fort Haight.',
 'Kenneth Haight looks down on Godrick.',
 'Kenneth Haight deems Godrick unworthy of ruling Limgrave.',
 "Kenneth Haight believes Godrick's actions during the Shattering were cowardly.",
 'Kenneth Haight believes Godrick does not possess the proper lineage required to rule.',
 "Kenneth Haight took back Fort Haight from Godrick's forces.",
 'Kenneth Haight saw the state Fort Haight was left in after taking it back.',
 'Kenneth Haight laments that he does not have the authority to rule Limgrave.',
 'Kenneth Haight goes on to look for an eligible candidate to rule Limgrave.',
 'Kenneth Haight finally comes across Nepheli Loux.',
 'Gostoc is the Gatekeeper of Stormveil Castle.',
 'Gostoc informs the Tarnished of a safer side passage to allow the Tarnished to enter Stormveil Castle undetected.',
 'Gostoc can be caught sneaking and following the Tarnished around in Stormveil Castle.',
 'Each time the Tarnished are defeated, Gostoc steals a portion of the Golden Runes that the Tarnished drop.',
 'Gostoc seems to do this with each Tarnished that comes to Stormveil Castle to challenge the shardbearer.',
 'Gostoc holds contempt for Godrick, the master of Stormveil Castle.',
 'Godrick has mistreated and looked down upon Gostoc.',
 "Much of Gostoc's dialogue reveals that Gostoc longs for freedom from Godrick and his duties.",
 'When Nepheli takes the throne, Gostoc is happy to return to his duties.',
 'Boc is a seamster.',
 'Boc is a demi-human outcast.',
 'Boc is often picked on for his looks.',
 'Boc looks up to his late mother.',
 "Boc's late mother was a skilled seamstress.",
 "Boc's late mother was one of the few people who cared for Boc.",
 'Boc was kicked out of his former home in the Costal Cave.',
 "Other demi-humans stole Boc's possessions.",
 'The Tarnished helps Boc take back his prized Sewing Needle.',
 'The Tarnished helps Boc take back his Tailoring Tools.',
 'Boc offers to tailor the armor of the Tarnished as compensation.',
 'Throughout his interactions with the Tarnished, Boc expresses unhappiness towards his looks.',
 'The Tarnished can grant Boc a Larval Tear to help change his appearance.',
 'The Tarnished can let Boc know he is accepted.',
 'Both outcomes, granting a Larval Tear or letting Boc know he is accepted, result in Boc being grateful.',
 'Brother Corhyn is a cleric of the Golden Order.',
 "Brother Corhyn's armor implies that he once foretold an inauspicious prophecy.",
 'Throughout his questline, Brother Corhyn shows high and unwavering faith in the Golden Order.',
 'Brother Corhyn is greatly interested in discovering the secrets of the Golden Order.',
 'Brother Corhyn leaves the Roundtable in search of Goldmask.',
 "After introducing Brother Corhyn to Goldmask, Brother Corhyn acts as Goldmask's scribe.",
 "Brother Corhyn translates and records Goldmask's various finger movements into written records.",
 'Brother Corhyn holds Goldmask in high regard.',
 "After learning of Goldmask's reservations towards the Golden Order, Brother Corhyn begins to question Goldmask's intentions.",
 'Goldmask is a famed scholar of Golden Order fundamentalism.',
 'Goldmask is one of many Tarnished called back to the Lands Between after the Shattering.',
 'Goldmask does not speak.',
 'Goldmask communicates through rhythmic hand and finger movements.',
 'Goldmask once lamented that hunters of Those Who Live in Death had been reduced to fanatics of the Golden Order.',
 'Goldmask lamented that hunters of Those Who Live in Death hunted simply for the sake of having an evil to fight against.',
 'The Tarnished aids Goldmask in better understanding the Golden Order throughout his questline.',
 'The Tarnished aids Goldmask in understanding the nature of Radagon.',
 'Goldmask aims to correct the imperfections that lie within the Golden Order.',
 'Goldmask concluded that the imperfections found within the Golden Order were due to the very gods being just as fickle as ordinary men.',
 'Goldmask used the Mending Rune of Perfect Order to reach his conclusion.',
 'Gowry is a Kindred of Rot disguised as an old sage.',
 "Gowry served as Millicent's caretaker during her childhood.",
 "It is uncertain what or where Gowry's real form is.",
 'Gowry returns to his shack as he was before most times after being attacked.',
 "After Malenia's Scarlet Aeonia bloomed in Caelid during the Shattering, Gowry dedicated his services to Malenia.",
 'Gowry believes that Malenia will bring about a new order called the Order of Rot.',
 'In the swamp of Aeonia, Gowry found Millicent and her sisters as babies.',
 'Gowry proceeded to raise Millicent and her sisters.',
 'Gowry hopes that when Malenia ascends to be the Goddess of Rot, Millicent and her sisters will be reborn as scarlet valkyries.',
 "Of all the sisters, Gowry saw the most potential in Millicent to follow in Malenia's footsteps.",
 "At the end of Millicent's quest, Gowry asks the Tarnished to aid Millicent's sisters in attacking Millicent.",
 "Gowry believes that the betrayal Millicent feels from the person she trusted the most will act as a catalyst for her to 'bloom'.",
 'Millicent is a daughter of Malenia.',
 'Millicent shares many striking similarities with Malenia.',
 'Millicent has bright red hair.',
 'Millicent is missing an arm due to her severe scarlet rot affliction.',
 "Millicent possesses skilled swordsmanship that resembles Malenia's style.",
 "Millicent feels a sense of familiarity within Gowry's Shack due to the scarlet rot.",
 'Millicent does not remember her childhood with Gowry.',
 'Millicent is cured using the Unalloyed Golden Needle.',
 'Millicent sets out on a journey to seek Malenia.',
 'Millicent hopes to aid Malenia in resisting the call of the scarlet rot.',
 'Millicent is ambushed by her sisters at Elphael before she is able to reach the Empyrean.',
 'Millicent may be ambushed by the Tarnished if they choose to do so.',
 "If the Tarnished defends Millicent instead, Millicent reveals that she is aware of Gowry's hopes for her.",
 'Millicent removes the golden needle.',
 'Millicent succumbs to the scarlet rot.',
 'Millicent does not want to live as someone other than herself.',
 'Irina is the blind daughter of Edgar.',
 'Irina escaped Castle Morne with the help of her father and some attendants at the castle.',
 'Irina cares much for her father.',
 'Irina implores the Tarnished to deliver a letter to her father.',
 "Irina's reunion with her father unfortunately never happens.",
 'Irina gets murdered.',
 "A large sword is left by Irina's corpse.",
 'Edgar is the Commander of Castle Morne.',
 'Edgar was ordained by Godrick.',
 'Edgar has a high sense of duty.',
 "Edgar stays behind to protect the castle's prized sword, the Grafted Blade Greatsword.",
 "The rest of the castle's attendants had fled from the Misbegotten rebellion.",
 'Edgar expresses regret over not protecting Irina after finding her body.',
 "Edgar swears vengeance towards Irina's killers.",
 'Edgar can later be found at Revengers Shack as an invader.',
 'Edgar drops the Shabriri Grape.',
 "It is speculated that Edgar succumbed to madness from Irina's death.",
 'Hyetta is a blind young woman.',
 'Hyetta resembles Irina.',
 'Despite being blind, Hyetta is able to perceive some form of light every time Hyetta consumes a Shabriri Grape.',
 'At first, Hyetta is disgusted by the fact that Shabriri Grapes are human eyes.',
 'Hyetta quickly comes to terms with the fact that Shabriri Grapes are human eyes.',
 'Hyetta affirms that consuming Shabriri Grapes is required for Hyetta to become a finger maiden.',
 'It seems that the Tarnished is not the only person bringing Hyetta Shabriri Grapes.',
 'Hyetta mentions that other beings with trembling hands and emaciated fingers have given Hyetta the Shabriri Grapes before.',
 "Successfully completing the Tarnished's quest and aiding Hyetta in becoming a Finger Maiden gives the Tarnished more information on the Three Fingers.",
 "Successfully completing the Tarnished's quest and aiding Hyetta in becoming a Finger Maiden gives the Tarnished more information on the Frenzied Flame.",
 'Shabriri is a mysterious figure who refers to himself as chaos incarnate.',
 "Shabriri inhabits Yura's body.",
 'Shabriri claims that Yura willingly gave his body away.',
 'The Tarnished meets Shabriri at the Mountaintops of the Giants.',
 'Shabriri tries to persuade the Tarnished into becoming the Lord of Frenzied Flame.',
 'Shabriri gives the Tarnished information on the Frenzied Flame Proscription.',
 'Shabriri was also the name of a man who previously had his eyes gouged out as punishment for the crime of slander.',
 "In time, Shabriri's eyes were filled with the flame of frenzy.",
 'According to the Howl of Shabriri, this was the first instance of the maddening sickness of frenzy in the Lands Between.',
 'Ranni the Witch is the daughter of Rennala and Radagon.',
 'Ranni the Witch took after her mother.',
 "Ranni the Witch discovered her own full moon called Ranni's Dark Moon.",
 'Ranni the Witch learnt cold sorceries from the mysterious Snow Witch.',
 'The mysterious Snow Witch was encountered by Ranni the Witch deep in the woods.',
 'Ranni the Witch has held Blaidd dearly since childhood.',
 'Ranni the Witch has held Iji dearly since childhood.',
 'At some point, Ranni the Witch defeated the Glinstone Dragon called Adula.',
 'Adula swore allegiance to Ranni the Witch after being defeated.',
 'Ranni the Witch was not born a demigod.',
 "Radagon's unity with Marika made Ranni the Witch eligible to be an Empyrean.",
 'Ranni the Witch did not want to be controlled by the Two Fingers.',
 'Ranni the Witch rejected her fate.',
 'Ranni the Witch masterminded the Night of the Black Knives as an act of rebellion.',
 'Ranni the Witch stole the Rune of Death during the Night of the Black Knives.',
 'Ranni the Witch imbued the power of the Rune of Death in the knives of the Black Knife Assassins.',
 "On the night of the assassination, Ranni the Witch's body died.",
 "Ranni the Witch's soul was transferred into a doll.",
 "The doll resembles Ranni the Witch's old master, Renna.",
 'Renna was the Snow Witch.',
 'Blaidd is the half-wolven Shadow of Ranni.',
 'Blaidd was granted to Ranni by the Two Fingers when Ranni became an Empyrean.',
 'Blaidd is an agent of the Two Fingers.',
 "Blaidd's loyalties lie only with Ranni.",
 'Blaidd considers Ranni as family.',
 'The sword that Blaidd carries is the Royal Greatsword.',
 "The Royal Greatsword was imbued with cold magic as proof of Blaidd's loyalty.",
 'If an Empyrean were to go against the will of the Two Fingers, their Shadow would go mad and oppose them.',
 'Blaidd would eventually face the fate of going mad.',
 'Even in madness, Blaidd continued to defy his fate.',
 'Blaidd remained faithful to Ranni.',
 'Iji is the only friendly Troll that the Tarnished encounters on their journey.',
 'Seluvis is a magic preceptor in service to the Carian Royal family.',
 'Seluvis is currently aiding Ranni in her search for the dark path.',
 'Seluvis helped Sellen in some way when Sellen was initially exiled from the academy.',
 'Sellen does not seem too fond of Seluvis when brought up.',
 'Seluvis is prickly at first.',
 "If the Tarnished discovers Seluvis's puppet collection and aids Seluvis in adding to it, Seluvis reveals his scheme.",
 "Seluvis's scheme is to betray Ranni.",
 'Seluvis wants to add Ranni, a demigod, to his puppet collection.',
 'It is speculated that Seluvis and Pidia have a connection.',
 'Seluvis and Pidia have a connection due to both their affinities towards puppets.',
 'Merchant Kale is one of the numerous nomadic merchants that the Tarnished can buy wares from.',
 'Merchant Kale is acquainted with Blaidd.',
 'Blaidd refers to Merchant Kale as a busybody.',
 'Merchant Kale describes the nomadic clan as spiteful.',
 "Merchant Kale describes the bodies as 'sick', 'maddened', 'husks of themselves', and 'hardly human anymore'.",
 'Merchant Kale finds out that his people were falsely accused of worshipping the Three Fingers.',
 'Merchant Kale discovers that his people were falsely accused of summoning the frenzied flame into the Lands Between.',
 'The false accusations fill Merchant Kale with spite towards the Greater Will.',
 'The false accusations fill Merchant Kale with spite towards the Golden Order.',
 'Merchant Kale would have refused further trade with the Tarnished until the Tarnished inherited the frenzied flame.',
 'After the Tarnished inherited the frenzied flame, Merchant Kale would try to be granted an audience with the Three Fingers.',
 'Witch-hunter Jerren was initially a nomadic wanderer.',
 'Jerren happened upon being a guest to the Carian royal family.',
 'During his time with the Carian royal family, Jerren was able to get acquainted with various members of the family.',
 'Notably, Jerren became acquainted with Ranni.',
 'Notably, Jerren became acquainted with Iji.',
 'Notably, Jerren became acquainted with Radahn.',
 'Jerren made a promise to Ranni and Iji to slay a longstanding enemy of the Carian family.',
 'The longstanding enemy of the Carian family is the Graven Witch Sellen.',
 'The Graven Witch Sellen committed atrocities against many of her fellow sorcerers.',
 'Before Jerren was able to fulfill his promise, General Radahn recruited Jerren into his army.',
 'Jerren served as a guest commander during the Shattering.',
 'Jerren is an excellent swordsman.',
 'The Flamberge that Jerren wields is one of the symbols of Redmane Castle.',
 'When the Tarnished first meets Jerren, Jerren heralds the beginning of the war festival.',
 'Sellen was said to be one of the most promising sorcerers in the history of the Raya Lucaria Academy.',
 'Sellen had a unique glintstone crown compared to other scholars the Tarnished encounters at the academy.',
 'Sellen was exiled from the Raya Lucaria Academy for her obsession and forbidden pursuit of the primeval current.',
 'According to Jerren, Sellen has killed many of her fellow sorcerers in her studies.',
 'Sellen was imprisoned in Witchbane Ruins by the Raya Lucaria Academy and the Carian Royal Family.',
 "If the Tarnished chooses to aid in Sellen's quest, they can help her inhabit a new unshackled body.",
 'The method to help Sellen inhabit a new body involves transplanting her primeval glintstone into another compatible body.',
 "Sellen's primeval glintstone is essentially her soul.",
 'Thops is a glintstone sorcerer.',
 'Thops is from the Academy of Raya Lucaria.',
 'Thops was looked down upon by his fellow scholars.',
 'Thops was nicknamed Thops the Bluntstone.',
 'Thops was nicknamed Thops the Bluntstone for not having enough talent to cast powerful sorceries.',
 'Thops longs to return to the Academy of Raya Lucaria to finish his studies.',
 'If the Tarnished chooses to aid Thops in his quest, Thops is able to complete his lifelong project.',
 "Thops creates the spell Thops's Barrier.",
 "Thops's Barrier is a uniquely defensive glintstone sorcery.",
 "Thops's Barrier is able to deflect both sorceries and incantations back at their caster.",
 "Thops's Barrier is a spell that is worthy of its own conspectus.",
 'Miriel is the Pastor of Vows.',
 'Miriel is a large turtle.',
 'Miriel is the steward of the Church of Vows.',
 'Miriel is a peaceful soul.',
 'Miriel teaches the Tarnished about Absolution.',
 'Miriel does not require Absolution if the Tarnished attack him.',
 "Miriel is well-versed in the history of Rennala and Radagon's union.",
 'Miriel is able to teach the Tarnished all manner of sorceries and incantations.',
 'Corhyn deems incantations not related to the Golden Order as heresy.',
 'Miriel is open-minded towards each of the sorcery and incantation scrolls the Tarnished gives him.',
 'Albus is a first generation Albinauric.',
 'Latenna is a first-generation Albinauric.',
 'Latenna is one of many wolf-riding Albinauric archers.',
 'Latenna was interrogated by an agent of Sir Gideon Ofnir.',
 'The interrogation may have been conducted by Sir Gideon Ofnir himself.',
 'The interrogation was about the second half of the Haligtree Secret Medallion.',
 "The interrogation led to the death of Latenna's faithful wolf.",
 "Latenna's faithful wolf is named Lobo.",
 'If the Tarnished approaches Latenna with the right half of the medallion, Latenna asks the Tarnished to take her to Apostate Derelict.',
 'Latenna offers information about the whereabouts of the left half of the secret medallion in exchange for being taken to Apostate Derelict.',
 'Upon arriving at Apostate Derelict, Latenna transfers a birthing droplet to a large Albinauric called Phillia.',
 'The exact purpose of the birthing droplet is unclear.',
 'Latenna mentions that the birthing droplet has something to do with creating life for the Albinaurics.',
 "Ensha is Sir Gideon Ofnir's silent right-hand man.",
 'Tanith is the consort to Lord Rykard.',
 'Tanith is the adoptive mother of Rya.',
 'Tanith worked as a dancer in an unnamed foreign land.',
 "Tanith caught Lord Rykard's eye.",
 'Tanith became the consort of Lord Rykard.',
 'Tanith was given the Tonic of Forgetfulness as an out.',
 "Tanith continued to stay by Lord Rykard's side.",
 'Tanith is now the Lady of the Volcano Manor.',
 'Tanith recruits Tarnished who are willing to rise against the Greater Will.',
 'Tanith recruits Tarnished to become recusants.',
 'The Tarnished can first meet Bernahl in Stormhill.',
 'Bernahl was said to be a Tarnished worthy of becoming Elden Lord.',
 'Bernahl was said to be carrying out his destined path without doubt.',
 "Bernahl's maiden threw herself into 'the fire'.",
 "There are a few speculations as to what Bernahl's maiden throwing herself into 'the fire' might mean.",
 "Some speculate that Bernahl's maiden succumbed to the flame of frenzy.",
 "Others speculate that similar to Melina, Bernahl's maiden was thrown into the Forge of the Giants as kindling for burning the Erdtree.",
 'The Tarnished can later find Bernahl as a recusant at the Volcano Manor.',
 'After defeating Rykard, Bernahl denounces the Greater Will.',
 'Bernahl vows to fell the Greater Will on behalf of his brother.',
 "Rya's real name is Zorayas.",
 'Patches the Untethered is a bandit.',
 'Patches the Untethered tricks unsuspecting people into various death traps.',
 'Patches the Untethered tricks unsuspecting people into entrapment schemes.',
 'If the Tarnished spares Patches the Untethered, Patches the Untethered will sell the Tarnished various goods.',
 'Patches the Untethered presumably obtains goods from the corpses of those he successfully tricked.',
 'Patches the Untethered mentions that his band of bandits comprises foot soldiers.',
 'Patches the Untethered mentions that his band of bandits comprises survivors of defeated armies.',
 "Patches' Emporium can be accessed when reaching Volcano Manor.",
 'Patches the Untethered has taken a liking to Tanith.',
 "Patches the Untethered endangers himself to obtain the Dancer's Castanets for Tanith.",
 "Patches the Untethered hopes that the Dancer's Castanets will put Tanith back to her right mind after Rykard's defeat.",
 'Diallos is the youngest son of House Hoslow.',
 'Diallos lives in the shadow of his elder brother, Juno Hoslow.',
 'Juno Hoslow is a formidable fighter.',
 'Diallos was all bark but no bite.',
 'Being all bark but no bite is unbefitting for a family whose motto revolves around bloodshed.',
 'Despite their differences, Diallos and Juno care for each other very much.',
 'Juno uses his position to dote on Diallos.',
 'Diallos looks up to Juno as a role model.',
 'Jar-Bairn is a young jar.',
 'Jar-Bairn lives in Jarburg.',
 'Jar-Bairn is one of the few living Jars capable of speaking to the Tarnished.',
 'Jar-Bairn is a warrior jar.',
 'Jar-Bairn is like his uncle Alexander.',
 'The Tarnished may find Jar-Bairn talking in his sleep.',
 'Jar-Bairn dreams about reuniting with Alexander.',
 'Jar-Bairn dreams about telling Alexander that he is a warrior jar too.',
 'Jar-Bairn dreams about poachers destroying the Living Pots at Jarburg.',
 'Jar-Bairn dreams about Diallos taking care of him.',
 'Iron Fist Alexander is an older Living Jar.',
 'Iron Fist Alexander left his home of Jarburg to seek great battle.',
 'Iron Fist Alexander left his home of Jarburg to hone his combat skills.',
 'Iron Fist Alexander is a warrior jar.',
 'Blackguard Big Boggart is a Tarnished.',
 'Blackguard Big Boggart is a former criminal.',
 'Blackguard Big Boggart sells boiled prawns and crabs at the Boilprawn Shack.',
 'Blackguard Big Boggart later sells boiled prawns and crabs just outside the royal capital.',
 'It is possible that Blackguard Big Boggart was previously convicted for thievery.',
 "Blackguard Big Boggart stole Rya's necklace when the Tarnished meets him.",
 'Blackguard Big Boggart used to be cellmates with Dung Eater.',
 'Blackguard Big Boggart witnessed Dung Eater defile the body of his friend with the Seedbed Curse.',
 'Witnessing Dung Eater defile the body of his friend with the Seedbed Curse was the most harrowing experience Blackguard Big Boggart had ever had.',
 'Dung Eater is a Tarnished.',
 'Dung Eater bears the heart of an Omen, as his armor suggests.',
 'Dung Eater was a merciless killer even before being brought back to the Lands Between.',
 'Dung Eater would defile the corpses of those he killed with Seedbed Curses.',
 'Dung Eater would curse the souls of those he killed to never be able to return to the Erdtree.',
 "Dung Eater's biggest aspiration is to defile and curse everyone in the Lands Between.",
 "Dung Eater's biggest aspiration is to defile and curse all future generations.",
 "Dung Eater's dream can be realized by aiding him in gestating the Mending Rune of the Fell Curse.",
 'Enia is a Finger Reader that the Tarnished encounters at the Roundtable Hold.',
 'Enia is an agent of the Greater Will.',
 'Enia is supportive of the Tarnished burning down the Erdtree when her Two Fingers stop communicating with her.',
 'Enia claims that before the Tarnished, another had gathered 2 Great Runes.',
 'Queen Marika, the Eternal is a Numen chosen and brought from her homeland to the Lands Between by the Greater Will.',
 'Queen Marika, the Eternal is a vassal of the Greater Will.',
 'Radagon of the Golden Order is characterized by his flowing red locks.',
 "Radagon is Queen Marika's second chosen consort.",
 'Radagon is a great warrior.',
 "Radagon's early life remains a mystery.",
 "Radagon's rise to prominence in the Golden Order is unknown.",
 'There is speculation that Radagon may be a smaller-sized Fire Giant.',
 "The speculation about Radagon being a Fire Giant is based on the descriptions of the Sword of Milos and Giant's Red Braid.",
 'Another theory is that Radagon was cursed to have red hair by the Fire Giants.',
 "The curse on Radagon was a result of the Golden Order's war with the Fire Giants.",
 'Radagon was said to have hated the red-tint of his hair.',
 'Godfrey was the first consort to Queen Marika.',
 'Godfrey was the first Elden Lord.',
 'Godfrey and Queen Marika had 3 children together.',
 "Godfrey's children were Godwyn the Golden and the Omen twins, Morgott and Mohg.",
 'Godfrey was originally known as Hoarah Loux.',
 'Hoarah Loux was a fierce warrior.',
 'Hoarah Loux had a strong bloodlust.',
 'Hoarah Loux was the chieftain of the badlands.',
 "Hoarah Loux was selected as Marika's first consort.",
 'Hoarah Loux took Beast Regent Serosh upon his back to quell his insatiable bloodlust.',
 'Hoarah Loux aimed to be more befitting of a Lord.',
 'When the Golden Order was established, Godfrey was tasked with leading several wars.',
 'Godfrey led wars to further the influence of the Golden Order.',
 'One of the wars led by Godfrey was against the Giants.',
 'Godfrey faced the Storm Lord alone during one of the wars.',
 "During Godfrey's reign, gladitorial combat in colosseums was commonplace in the Lands Between.",
 'Gladitorial combat was held as rituals to honor the Erdtree.',
 "The practice of gladitorial combat died out when Radagon became Marika's next consort.",
 'After Godfrey won his last campaign, there were no worthy opponents left to battle with.',
 "Marika took away the Erdtree's blessing from Godfrey and countless others.",
 'Godfrey and countless others were turned into Tarnished.',
 'Godfrey led the Tarnished out of the Lands Between in a journey referred to as the Long March.',
 "Godfrey's axe was broken in a battle during the Long March.",
 'After the Long March ended, Godfrey reverted back to becoming a simple warrior.',
 'Godfrey still carried Serosh on his back after reverting to a simple warrior.',
 'Rennala was the Queen of the full moon.',
 'Morgott is one of two Omen twins.',
 'Morgott was born of Queen Marika and Godfrey.',
 'Despite being locked away and shunned, Morgott still loved the Order.',
 'Morgott ruled the capital in the shadows as the Unveiled Monarch.',
 'During the Second Defense of Leyndell, Morgott successfully defended the capital and the Erdtree from invading demigods.',
 "Morgott's dialogue suggests he attempted to claim the throne of the Elden Lord.",
 'The Erdtree warded Morgott off from claiming the throne of the Elden Lord.',
 'The Tarnished will first encounter Morgott under the pseudonym, Margit.',
 'Morgott prevents the Tarnished from challenging Godrick in Stormveil Castle.',
 'Morgott prevents the Tarnished from obtaining one of many Great Runes required to enter the capital.',
 'Mohg is known as the Lord of Blood.',
 'Mohg is the son of Queen Marika.',
 "Mohg is the son of Godfrey, who is Queen Marika's first consort.",
 'Mohg has a twin brother.',
 'Mohg fully embraced his accursed Omen blood and traits.',
 "Mohg's twin brother distanced himself from his Omen nature.",
 'Mohg was shackled deep within the Subterranean Shunning-Grounds.',
 'Mohg encountered the Formless Mother while imprisoned underground.',
 'The Formless Mother is an outer god like the Greater Will.',
 "The encounter with the Formless Mother caused Mohg's accursed omen blood to ignite.",
 "The ignition of Mohg's accursed omen blood gave him the ability to cast bloodflame incantations.",
 "Mohg used his spear, known as Mohgwyn's Sacred Spear, to communicate with the Formless Mother.",
 'At some point, Mohg managed to escape from the Subterranean Shunning-Grounds.',
 'Mohg established the Mohgwyn Palace in a secluded part of the Siofra River.',
 'Mohg recruited multiple people to become followers of the upcoming Mohgwyn Dynasty.',
 'Mohg offered deals to some followers, such as Bloody Finger Okina.',
 'Mohg kidnapped other followers, such as the War Surgeons.',
 'Mohg is not an Empyrean himself.',
 'Mohg is unable to ascend to godhood.',
 'Mohg hoped to claim the title of monarch by raising empyrean Miquella to full godhood.',
 'Mohg aimed to become the consort of empyrean Miquella.',
 'Mohg stole the slumbering Miquella from inside the Haligtree.',
 'Mohg attempted to rouse empyrean Miquella with his accursed blood.',
 'Miquella never woke from his slumber, regardless of how much blood Mohg offered.',
 'Miquella never woke from his slumber, regardless of how much time he shared his bedchambers with Mohg.',
 'Rykard is known as the lord of blasphemy.',
 'Praetor Rykard is Lord of the Volcano Manor.',
 'Praetor Rykard is a ruthless justiciar.',
 'Praetor Rykard is the son of Rennala and Radagon.',
 "Praetor Rykard became a demigod after Radagon's unity with Queen Marika.",
 'Rykard presides over Mt. Gelmir.',
 'Rykard was served by the Gelmir Knights.',
 'The lava sorceries that the Tarnished can learn were created by Rykard.',
 'Some of the lava sorceries created by Rykard are old hexes from Mt. Gelmir that he turned into practical sorceries.',
 'At some point, Rykard met Tanith in a foreign land.',
 'Rykard brought Tanith back to the Lands Between to be his consort.',
 'Rykard had a hand in the Night of the Black Knives.',
 "The extent of Rykard's involvement in the Night of the Black Knives is unclear.",
 "The Blasphemous Claw was an item rewarded by Rykard's sister Ranni.",
 'The Blasphemous Claw allowed Rykard to challenge Maliketh as a last resort.',
 "The description for the Taker's Cameo implies that Rykard believed that Marika and her Order ruled by force.",
 'Rykard swore himself to blasphemy and sought to overthrow Marika and her Order.',
 "Rykard's ambition drew many towards him.",
 'The ancient people of Mt. Gelmir worshipped a powerful serpent god.',
 'The ancient people of Mt. Gelmir offered sacrifices to the powerful serpent god.',
 'Rykard encountered the God-Devouring Serpent.',
 'Rykard offered himself and his Great Rune up as sacrifices.',
 "Rykard's sacrifices granted him immortality.",
 "Rykard's immortality allowed him to grow and devour people and gods alike for all eternity.",
 "Rykard's fall into greed and glutinous depravity caused most of his followers to turn against him.",
 'Tanith was a notable exception to the followers who turned against Rykard.',
 'Those who were once Gelmir Knights sought out the Serpent-Hunter.',
 'The Serpent-Hunter is a great spear designed to hunt the immortal serpent.',
 'The former Gelmir Knights sought to put an end to their Lord, Rykard.',
 'The former Gelmir Knights found the mythical weapon, the Serpent-Hunter.',
 'The former Gelmir Knights were unsuccessful in defeating Rykard.',
 "The corpses holding the Serpent-Hunter are found in Rykard's boss room.",
 "When the Tarnished visits the Volcano Manor, they can find its members following Rykard's blasphemous path.",
 'It is later revealed that those who proved themselves as recusants were granted an audience with Rykard.',
 "Those who proved themselves as recusants became part of Rykard's family by being devoured by the great serpent himself.",
 'The Volcano Manor faction houses a group of Recusant Tarnished.',
 'The Mohgwyn Dynasty is a faction.',
 'The Mohgwyn Dynasty faction is led by Mohg.',
 'Mohg is known as the Lord of Blood.',
 'The Mohgwyn Dynasty faction is similar to the Volcano Manor.',
 'Those in service to the Mohgwyn Dynasty faction invade other Tarnished.',
 'Those in service to the Mohgwyn Dynasty faction renounce the Greater Will.',
 'Bloodshed is the only motive for invasion in the Mohgwyn Dynasty faction.',
 'The beginnings of the Mohgwyn Dynasty can be found in Mohgwyn Palace.',
 'The remaining members of the Carian Royal Family Faction are Rennala, Ranni, and their trusted advisors.',
 'Those Who Live In Death refer to the numerous undead plaguing the Lands Between.',
 'The existence of Those Who Live In Death defies the tenets of the prevalent Golden Order.',
 'Those Who Live In Death live in persecution.',
 'Those in the faction of Those Who Live In Death are empathetic towards Those Who Live In Death.',
 'Those in the faction of Those Who Live In Death join in awaiting the rise of their Lord.',
 'The Golden Order Faction was established by Queen Marika.',
 'The Golden Order Faction was established by the Greater Will.',
 'The Golden Order Faction is the most dominant faction in the Lands Between.',
 'The tenets of the Golden Order Faction govern the rules and status quo to be practiced by its followers.',
 'Many followers of the Golden Order Faction follow its tenets blindly.',
 'A few members of the Golden Order Faction are starting to question the infallibility of the Order.',
 'Frenzied Flame Faction is a covert faction.',
 'Frenzied Flame Faction is led by the Three Fingers.',
 'Those in the Frenzied Flame Faction await one who would take up the mantle of Lord of Chaos.',
 'Please provide the content you would like me to decompose, and I will assist you with that.']