eldenring_propositions = ['Lore in Elden Ring covers all the information related to the world of Elden Ring.',
 'Lore in Elden Ring covers all the information related to the mythos of Elden Ring.',
 'Lore in Elden Ring includes past events that occurred long ago.',
 'Lore in Elden Ring includes the history of the Lands Between.',
 'Lore in Elden Ring includes the mystery of the elusive Elden Ring.',
 'All information related to the world, mythos, past events, history, and mystery can be found in the lore of Elden Ring.',
 'This page contains heavy spoilers.',
 'The Mythos of Elden Ring was written by George R. R. Martin.',
 'Elden Ring is a video game.',
 'Elden Ring has a lore overview.',
 'The storyteller folds her slender hands.',
 'The storyteller folds both pairs of her hands.',
 'The storyteller speaks.',
 'The storyteller states that the events happened an age ago.',
 'The storyteller recalls the events as true.',
 'The Lands Between is the world of Elden Ring.',
 'Limgrave is one of the areas in the game.',
 'Elden Ring is a video game.',
 "Hidetaka Miyazaki stated that the Lands Between is supposed to invoke a feeling of something that's very mysterious and very ethereal.",
 'Hidetaka Miyazaki hopes that when players play the game, they are going to experience that feeling.',
 'Melina is one of the first people the Tarnished encounters on their journey.',
 'Melina maintains an air of mystery throughout the game.',
 'Melina does not have a physical form.',
 "Melina acts as the Tarnished's Finger Maiden in exchange for taking Melina to the Erdtree.",
 'Melina later asks the Tarnished to take her to the Mountaintops of the Giants.',
 'Melina approaches the Tarnished to aid Melina in her search for her purpose.',
 "Melina's purpose was given to her by Melina's mother.",
 'Melina believes her mother can be found at the base of the Erdtree.',
 "Many speculate that Melina's mother is Marika.",
 'When summoned, Melina wields the Blade of Calling.',
 'The Blade of Calling is a dagger that was previously owned by the kindling maiden.',
 "Melina's role as kindling is fitting when the Erdtree is burnt down.",
 "Speaking with Melina at various Sites of Grace reveals Melina's ability to recall echoes of Queen Marika's past actions and words.",
 "Melina offers echoes of Queen Marika's past actions and words in lieu of a 'maiden's guidance'.",
 'Melina holds contempt for the Frenzied Flame.',
 'Melina believes that whoever lords over the chaos and damage brought by the Frenzied Flame is no Lord at all.',
 'If the Tarnished takes the Frenzied Flame before the event at the Forge of the Giants, Melina will leave the Tarnished.',
 'Melina will threaten to deliver the Tarnished Destined Death once the Tarnished becomes Lord of the Frenzied Flame.',
 'The White Masks encountered in Mohgwyn Palace were initially abducted by Mogh.',
 'Mogh is known as the Lord of Blood.',
 'The White Masks were turned into Bloody Fingers through an unknown ritual.',
 "The unknown ritual involved Mogh's accursed Omen blood.",
 'Of the four White Masks, the Tarnished encounters in the game, only Varre was able to withstand and tame the accursed blood.',
 'Varre was abducted by the Lord of Blood.',
 'Varre remains loyal to the Mohgwyn Dynasty.',
 'Varre tries to indoctrinate the Tarnished into the Mohgwyn Dynasty.',
 'Even as Varre is dying at the end of his questline, he is forsaken by his Lord.',
 'Varre calls out to Mohg at the end of his questline.',
 'Varre blesses the Mohgwyn Dynasty.',
 'Bloody Finger Hunter Yura is a samurai from the Land of Reeds.',
 "Bloody Finger Hunter Yura's purpose is to hunt down Bloody Fingers.",
 "Bloody Finger Hunter Yura's biggest target is Eleonora, Violet Bloody Finger.",
 'Sorcerer Rogier is a Tarnished.',
 'Sorcerer Rogier has an easy-going nature.',
 'Sorcerer Rogier is said to be a wise and powerful sorcerer by his old travelling companion, D.',
 'Sorcerer Rogier was once a scholar.',
 'Sorcerer Rogier was seeking the truth behind the Night of the Black Knives.',
 "Sorcerer Rogier's scholarly pursuits eventually brought him under Stormveil Castle.",
 'Sorcerer Rogier found and disturbed a corpse under Stormveil Castle.',
 'Disturbing the corpse caused Sorcerer Rogier to be afflicted with Death.',
 'D sees Those Who Live in Death as a threat against the Golden Order.',
 'Sorcerer Rogier is empathetic towards Those Who Live in Death.',
 'Sorcerer Rogier believes Those Who Live in Death have committed no offence.',
 "By finishing Sorcerer Rogier's quest, the Tarnished is able to help Sorcerer Rogier reveal many insights about the night of the assassination.",
 'Sorcerer Rogier finally succumbs to his affliction.',
 'Fia is a Tarnished Deathbed Companion.',
 'D is a devout follower of the Golden Order.',
 'D hunts Those Who Live in Death.',
 'D notably hunts Tibia Mariners for their Deathroot.',
 'D has a twin brother.',
 "The dialogue of D's twin brother suggests his name is Darian.",
 'D and Darian have separate bodies and separate minds.',
 'D and Darian share the same soul.',
 'One twin cannot be conscious when the other is conscious.',
 'Other Orders would have seen D and Darian as cursed beings.',
 'D and Darian found comfort in the Golden Order.',
 'The Golden Order is the one Order that does not see them as cursed beings.',
 'D states that Those Who Live in Death go against the principles of the Golden Order.',
 'D states that Those Who Live in Death must be exterminated.',
 'D is known as the Beholder of Death.',
 'D has a Twin Brother.',
 "The name of D's Twin Brother is inferred to be Devin from D's voicelines.",
 "D's Twin Brother can be found slumbering in the Siofra Aqueduct while D is alive.",
 "D's Twin Brother can be found grieving in the Siofra Aqueduct when D is dead.",
 "D's Twin Brother is unable to talk and interact with D.",
 "D and D's Twin Brother seem to be close.",
 "D's Twin Brother swears revenge against D's killer.",
 "D's Twin Brother's potential targets for revenge include Fia or the Tarnished.",
 "D's Twin Brother swears revenge when given D's armor set.",
 'Gurranq is a large beastman who hungers for Deathroot.',
 'Roderika is a Tarnished driven away from her home across the sea.',
 'The cloak that Roderika wears implies that Roderika used to be a member of royalty.',
 'At some point upon arriving at the Lands Between, Roderika happened upon White Mask Varre.',
 'White Mask Varre gave Roderika the same advice as he gives the Tarnished at the beginning of their journey.',
 'White Mask Varre advised Roderika to seek Godrick and his Great Rune at Stormveil Castle.',
 'Upon arriving at Stormhill, the men escorting Roderika were taken and sacrificed for grafting.',
 'Roderika feels guilt about the fact that Roderika is too afraid to join the men who were sacrificed.',
 "Roderika moves to the Roundtable Hold to find purpose after receiving the hopeful echoes of Roderika's men through the Chrysalids' Memento.",
 "Smithing Master Hewg recognises Roderika's potential for spirit tuning through Roderika's eyes.",
 'Smithing Master Hewg trains Roderika to be a skillful spirit tuner with a bit of encouragement from the Tarnished.',
 'Roderika and Smithing Master Hewg become close.',
 "Even as the Roundtable Hold is burning down, Roderika stays behind with Smithing Master Hewg to repay Smithing Master Hewg's kindness.",
 'Smithing Master Hewg is a misbegotten chained and imprisoned at the Roundtable Hold.',
 'Smithing Master Hewg is tasked by Queen Marika to smith a weapon strong enough to kill a god.',
 'Smithing Master Hewg makes the task of smithing a weapon strong enough to kill a god his life goal.',
 'Smithing Master Hewg strongly believes that the Tarnished will be the one to become Elden Lord.',
 'Smithing Master Hewg will say that the Tarnished will be the one to become Elden Lord before he completely loses his memory.',
 'Nepheli Loux is the adoptive daughter of Sir Gideon Ofnir.',
 'Sir Gideon Ofnir took Nepheli Loux in when Nepheli Loux lost the guidance of grace.',
 'Nepheli Loux became a Tarnished.',
 'Nepheli Loux is a skilled warrior.',
 'Nepheli Loux believes in standing up and enacting justice for the weak and oppressed.',
 'Nepheli Loux once believed that Sir Gideon Ofnir held the same beliefs.',
 'Nepheli Loux learned that Sir Gideon Ofnir was the mastermind behind the attack on the Village of the Albinaurics.',
 "After learning about Sir Gideon Ofnir's actions, Nepheli Loux loses faith in Sir Gideon Ofnir.",
 'It is speculated that Nepheli Loux has ties with the first Elden Lord, Godfrey.',
 'Nepheli Loux is speculated to have ties with the Golden Lineage.',
 'Nepheli Loux bears the same last name as Hoarah Loux.',
 'Kenneth Haight deems Nepheli Loux worthy of taking up the mantle of leader of Limgrave.',
 'Kenneth Haight is a member of the Erdtree royalty.',
 'Kenneth Haight is a self-proclaimed rightful leader of Limgrave.',
 'Kenneth Haight is the owner of Fort Haight.',
 'Kenneth Haight looks down on Godrick.',
 'Kenneth Haight deems Godrick unworthy of ruling Limgrave.',
 "Kenneth Haight believes Godrick's actions during the Shattering were cowardly.",
 'Kenneth Haight believes Godrick does not possess the proper lineage required to rule.',
 "Kenneth Haight took back Fort Haight from Godrick's forces.",
 'Kenneth Haight saw the state Fort Haight had been left in.',
 'Kenneth Haight laments that he does not have the authority to rule Limgrave.',
 'Kenneth Haight goes on to look for an eligible candidate to rule Limgrave.',
 'Kenneth Haight finally comes across Nepheli Loux.',
 'Gatekeeper Gostoc is the Gatekeeper of Stormveil Castle.',
 'Gatekeeper Gostoc informs the Tarnished of a safer side passage to allow the Tarnished to enter Stormveil Castle undetected.',
 'Gatekeeper Gostoc can be caught sneaking and following the Tarnished around in Stormveil Castle.',
 'Each time the Tarnished are defeated, Gostoc steals a portion of the Golden Runes the Tarnished drop.',
 'Gostoc seems to do this with each Tarnished that comes to Stormveil Castle to challenge the shardbearer.',
 'Gatekeeper Gostoc holds contempt for Godrick, the master of Stormveil Castle.',
 'Gatekeeper Gostoc has been mistreated and looked down upon by Godrick.',
 "Much of Gatekeeper Gostoc's dialogue reveals that he longs for freedom from his master and duties.",
 'When Nepheli takes the throne, Gatekeeper Gostoc is happy to return to his duties.',
 'Boc is a seamster.',
 'Boc is a demi-human outcast.',
 'Boc is often picked on for his looks.',
 'Boc looks up to his late mother.',
 "Boc's late mother was a skilled seamstress.",
 "Boc's late mother was one of the few people who cared for Boc.",
 'Boc was kicked out of his former home in the Costal Cave.',
 "Other demi-humans stole Boc's possessions.",
 'The Tarnished helps Boc take back his prized Sewing Needle.',
 'The Tarnished helps Boc take back his Tailoring Tools.',
 "Boc offers to tailor the Tarnished's armor as compensation.",
 'Boc expresses unhappiness towards his looks throughout his interactions with the Tarnished.',
 "The Tarnished can grant Boc a Larval Tear to help change Boc's appearance.",
 'The Tarnished can let Boc know he is accepted.',
 'Both granting a Larval Tear and letting Boc know he is accepted have different outcomes.',
 'Boc is grateful for both outcomes.',
 'Brother Corhyn is a cleric of the Golden Order.',
 "Brother Corhyn's armor implies that he once foretold an inauspicious prophecy.",
 'The specifics of the inauspicious prophecy foretold by Brother Corhyn are unclear.',
 'Throughout his questline, Brother Corhyn shows high and unwavering faith in the Golden Order.',
 'Brother Corhyn is greatly interested in discovering the secrets of the Golden Order.',
 'Brother Corhyn leaves the Roundtable in search of Goldmask.',
 'Goldmask is a great scholar of Golden Order fundamentalism.',
 "After introducing Brother Corhyn to Goldmask, Brother Corhyn acts as Goldmask's scribe.",
 "Brother Corhyn translates and records Goldmask's various finger movements into written records.",
 'Brother Corhyn holds Goldmask in high regard.',
 "Brother Corhyn learns of Goldmask's reservations towards the Golden Order.",
 "After learning of Goldmask's reservations, Brother Corhyn begins to question Goldmask's intentions.",
 'Goldmask is a famed scholar of Golden Order fundamentalism.',
 'Goldmask is one of many Tarnished called back to the Lands Between after the Shattering.',
 'Goldmask does not speak.',
 'Goldmask communicates through rhythmic hand and finger movements.',
 'Goldmask once lamented that hunters of Those Who Live in Death had been reduced to fanatics of the Golden Order.',
 'Goldmask lamented that hunters of Those Who Live in Death hunted simply for the sake of having an evil to fight against.',
 'The Tarnished aids Goldmask in better understanding the Golden Order throughout his questline.',
 'The Tarnished aids Goldmask most notably in the nature of Radagon.',
 'Goldmask seeks to correct the imperfections that lie within the Golden Order.',
 'Goldmask concluded that the imperfections found within the Golden Order were due to the very gods being just as fickle as ordinary men.',
 'Goldmask utilized the Mending Rune of Perfect Order to reach his conclusion.',
 'Gowry is a Kindred of Rot disguised as an old sage.',
 "Gowry was Millicent's caretaker as a child.",
 "It is uncertain what Gowry's real form is.",
 'Gowry returns to his shack most times after being attacked.',
 'Gowry dedicated his services to Malenia.',
 'Gowry believes that Malenia will bring about a new order called the Order of Rot.',
 'In the swamp of Aeonia, Gowry found Millicent and presumably her sisters as babies.',
 'Gowry proceeded to raise Millicent and her sisters.',
 'Gowry hopes that when Malenia ascends to be the Goddess of Rot, Millicent and her sisters will be reborn as scarlet valkyries.',
 "Of all the sisters, Gowry saw the most potential in Millicent to follow in Malenia's footsteps.",
 "At the end of Millicent's quest, Gowry asks the Tarnished to aid Millicent's sisters in attacking Millicent.",
 "Gowry believes that the betrayal Millicent feels from the person she trusted the most will act as a catalyst for her to 'bloom'.",
 'Millicent is a daughter of Malenia.',
 'Millicent shares many striking similarities with her mother.',
 'Millicent has bright red hair.',
 'Millicent has a missing arm due to a severe scarlet rot affliction.',
 "Millicent possesses skilled swordsmanship that resembles her mother's style.",
 "Millicent feels a sense of familiarity within Gowry's Shack due to the scarlet rot.",
 'Millicent does not remember her childhood with Gowry.',
 'Millicent is cured using the Unalloyed Golden Needle.',
 'After being cured, Millicent sets out on a journey to seek Malenia.',
 'Millicent hopes to aid Malenia in resisting the call of the scarlet rot.',
 'Millicent is ambushed by her sisters at Elphael.',
 'Millicent may be ambushed by the Tarnished if they choose.',
 'If the Tarnished defends Millicent instead, Millicent reveals that she is aware of what Gowry hoped she would bloom into.',
 'Millicent removes the golden needle.',
 'Millicent succumbs to the scarlet rot.',
 'Millicent does not want to live as someone other than herself.',
 'Irina is the blind daughter of Edgar.',
 'Irina cares much for her father.',
 'Irina implores the Tarnished to deliver a letter persuading Edgar to leave the castle.',
 "Irina and Edgar's reunion unfortunately never happens.",
 'Irina gets murdered.',
 'Edgar is the Commander of Castle Morne.',
 'Edgar was ordained by Godrick.',
 'Edgar has a high sense of duty.',
 "Edgar stays behind to protect the castle's prized sword.",
 "The castle's prized sword is the Grafted Blade Greatsword.",
 "The rest of the castle's attendants fled from the Misbegotten rebellion.",
 "After finding Irina's body, Edgar expresses regret over not protecting Irina.",
 "Edgar swears vengeance towards Irina's killers.",
 'Edgar can later be found at Revengers Shack as an invader.',
 'Edgar drops Shabriri Grape.',
 "It is speculated that Edgar succumbed to madness from Irina's death.",
 'Hyetta is a blind young woman.',
 'Hyetta resembles Irina.',
 'Despite being blind, Hyetta is able to perceive some form of light every time Hyetta consumes a Shabriri Grape.',
 'At first, Hyetta is disgusted by the fact that Shabriri Grapes are human eyes.',
 'Hyetta quickly comes to terms with the fact that Shabriri Grapes are human eyes.',
 'Hyetta affirms that consuming Shabriri Grapes is required for Hyetta to become a finger maiden.',
 'It seems that the Tarnished is not the only person bringing Shabriri Grapes to Hyetta.',
 'Hyetta mentions that other beings with trembling hands and emaciated fingers have given Hyetta Shabriri Grapes before.',
 'Successfully completing the quest for Hyetta aids Hyetta in becoming a Finger Maiden.',
 'Successfully completing the quest for Hyetta gives the Tarnished more information on the Three Fingers.',
 'Successfully completing the quest for Hyetta gives the Tarnished more information on the Frenzied Flame.',
 'Shabriri is a mysterious figure who refers to himself as chaos incarnate.',
 'Shabriri inhabits the body of Yura.',
 'Shabriri claims that Yura willingly gave his body away.',
 'The Tarnished meets Shabriri at the Mountaintops of the Giants.',
 'Shabriri tries to persuade the Tarnished into becoming the Lord of Frenzied Flame.',
 'Shabriri gives the Tarnished information on the Frenzied Flame Proscription.',
 'Shabriri was also the name of a man who previously had his eyes gouged out as punishment for his crime of slander.',
 'In time, the eyes of Shabriri were filled with the flame of frenzy.',
 'According to the Howl of Shabriri, this was the first instance of the maddening sickness of frenzy in the Lands Between.',
 'Ranni the Witch is the daughter of Rennala and Radagon.',
 'Blaidd is the half-wolven Shadow of Ranni.',
 'Blaidd was granted to Ranni by the Two Fingers when Ranni became an Empyrean.',
 'Blaidd is an agent of the Two Fingers.',
 "Blaidd's loyalties lie only with Ranni.",
 'Blaidd considers Ranni as family.',
 'Blaidd carries a sword named the Royal Greatsword.',
 "The Royal Greatsword was imbued with cold magic as proof of Blaidd's loyalty.",
 'Blaidd faced the fate of madness due to his loyalty to Ranni.',
 'Even in madness, Blaidd continued to defy his fate.',
 'Blaidd remained faithful to Ranni.',
 'Iji is the only friendly Troll that the Tarnished encounters on their journey.',
 'Iji has two roles within the Carian royal family.',
 "Iji is the royal family's blacksmith.",
 'According to Jerren, the blades smithed by Iji were blunt.',
 'The blades smithed by Iji were able to resist decay when faced against scarlet rot.',
 "Iji also acts as Ranni's war counselor.",
 'Iji provides Ranni and those under Ranni with guidance on the lost city of Nokron.',
 'Iji cares very much for Blaidd.',
 'Iji cares very much for Ranni.',
 'Iji has watched over Blaidd and Ranni since they were children.',
 'Iji is loyal towards Ranni.',
 "Iji's Mirrorhelm seems to imply that Iji feared the consequence of his treachery against the Greater Will.",
 'Seluvis is a magic preceptor.',
 'Seluvis is in service to the Carian Royal family.',
 'Seluvis is currently aiding Ranni in her search for the dark path.',
 'Seluvis helped Sellen in some way when Sellen was initially exiled from the academy.',
 'Sellen does not seem too fond of Seluvis when Seluvis is brought up.',
 'Seluvis is prickly at first.',
 "If the Tarnished discovers Seluvis's puppet collection and aids Seluvis in adding to it, Seluvis reveals his scheme.",
 "Seluvis's scheme is to betray Ranni.",
 "Seluvis's scheme is to add Ranni, a demigod, to his puppet collection.",
 'It is speculated that Seluvis and Pidia have a connection.',
 'Seluvis and Pidia have a connection due to both their affinities towards puppets.',
 'Merchant Kale is one of the numerous nomadic merchants that the Tarnished can buy wares from.',
 'Merchant Kale is acquainted with Blaidd.',
 'Blaidd refers to Merchant Kale as a busybody.',
 'Merchant Kale describes the nomadic clan as spiteful.',
 "Pieces of Merchant Kale's cut quest have been found by community members.",
 'In the cut content, the Tarnished would have aided Merchant Kale in discovering what happened to the Great Caravan.',
 'Merchant Kale would have commented on the bodies of the nomad clan found on the way to the underground area.',
 "Merchant Kale described the bodies as 'sick', 'maddened', 'husks of themselves', and 'hardly human anymore'.",
 'Merchant Kale finds out that his people were falsely accused of worshipping the Three Fingers.',
 'Merchant Kale discovers that his people were falsely accused of summoning the frenzied flame into the Lands Between.',
 'The false accusations fill Merchant Kale with spite towards the Greater Will and the Golden Order.',
 'Merchant Kale would have refused further trade with the Tarnished until the Tarnished inherited the frenzied flame.',
 'After the Tarnished inherited the frenzied flame, Merchant Kale would try to be granted an audience with the Three Fingers.',
 'Jerren was initially a nomadic wanderer.',
 'Sellen was said to be one of the most promising sorcerers in the history of the Raya Lucaria Academy.',
 'Sellen had a unique glintstone crown from other scholars the Tarnished encounters at the Raya Lucaria Academy.',
 'Sellen was exiled from the Raya Lucaria Academy for her obsession and forbidden pursuit of the primeval current.',
 'During her quest, Sellen mentions two other primeval sorcerers, Master Lusat and Master Azur.',
 'Sellen was imprisoned in Witchbane Ruins by the Raya Lucaria Academy and the Carian Royal Family.',
 "If the Tarnished chooses to aid in Sellen's quest, they can help Sellen inhabit a new unshackled body.",
 'The process to help Sellen inhabit a new unshackled body involves transplanting her primeval glintstone into another compatible body.',
 "Sellen's primeval glintstone is essentially her soul.",
 'Thops is a glintstone sorcerer from the Academy of Raya Lucaria.',
 'Thops was looked down upon by his fellow scholars.',
 'Thops was nicknamed Thops the Bluntstone.',
 'Thops was nicknamed Thops the Bluntstone for not having enough talent to cast powerful sorceries.',
 'Thops longs to return to the Academy of Raya Lucaria to finish his studies despite the animosity from fellow scholars.',
 'If the Tarnished chooses to aid Thops in his quest, Thops is able to complete his lifelong project.',
 "Thops creates the spell Thops's Barrier.",
 "Thops's Barrier is a uniquely defensive glintstone sorcery.",
 "Thops's Barrier is able to deflect both sorceries and incantations back at their caster.",
 "Thops's Barrier is a spell that is worthy of its own conspectus.",
 'Miriel is a large turtle.',
 'Miriel is the steward of the Church of Vows.',
 'Miriel is a peaceful soul.',
 'Miriel teaches the Tarnished about Absolution.',
 'Miriel does not require Absolution if the Tarnished attack him.',
 "Miriel is well-versed in the history of Rennala and Radagon's union.",
 'Miriel is able to teach the Tarnished all manner of sorceries and incantations.',
 'Miriel is open-minded towards each of the sorcery and incantation scrolls the Tarnished gives him.',
 'Albus is a first generation Albinauric.',
 'Latenna is a first-generation Albinauric.',
 'Latenna is one of many wolf-riding Albinauric archers.',
 "Ensha is Sir Gideon Ofnir's silent right-hand man.",
 'Ensha has an armor set called the Royal Remains Set.',
 'Ensha has a weapon called the Clinging Bone.',
 'The armor set and weapon seem to suggest that Ensha is the reanimated remains of a king referred to as the Soulless King.',
 'Tanith is the consort to Lord Rykard.',
 'Tanith is the adoptive mother of Rya.',
 'Tanith worked as a dancer in an unnamed foreign land.',
 "Tanith caught Lord Rykard's eye and became his consort.",
 "Even after Lord Rykard's men turned against him, Tanith continued to stay by his side.",
 "Even after Tanith was given the Tonic of Forgetfulness as an out, she continued to stay by Lord Rykard's side.",
 'Tanith is now the Lady of the Volcano Manor.',
 'Tanith recruits Tarnished who are willing to rise against the Greater Will.',
 'Tanith recruits Tarnished to become recusants.',
 'The Tarnished can first meet Bernahl, the Ash of War teacher, in Stormhill.',
 'Bernahl was said to be a Tarnished worthy of becoming Elden Lord.',
 'Bernahl was carrying out his destined path without doubt.',
 "Bernahl's maiden threw herself into 'the fire'.",
 "There are a few speculations as to what Bernahl's maiden throwing herself into 'the fire' might mean.",
 "Some speculate that Bernahl's maiden succumbed to the flame of frenzy.",
 "Others speculate that similar to Melina, Bernahl's maiden was thrown into the Forge of the Giants as kindling for burning the Erdtree.",
 'The Tarnished can later find Bernahl as a recusant at the Volcano Manor.',
 'After defeating Rykard, Bernahl denounces the Greater Will.',
 'Bernahl vows to fell the Greater Will on behalf of his brother.',
 "Rya's real name is Zorayas.",
 'Rya is a Man-Serpent disguised as a human.',
 'Rya is the scout for the Volcano Manor.',
 "Only the Tarnished knows of Rya's true form.",
 "Tanith is Rya's adoptive mother.",
 "Tanith knows of Rya's true form.",
 'Rya holds great regard for Tanith.',
 "Rya strongly believes in Tanith's work.",
 'Rya strongly believes in the endeavors of the Volcano Manor.',
 "Rya's quest involves finding the truth behind her origins.",
 'Tanith told Rya that she was born by the grace of a great king.',
 "Rya notices that the Volcano Manor isn't all that it seems.",
 'Rya confronts Tanith about the secrets of the Volcano Manor.',
 'Rya confronts Tanith about other secrets that Tanith has been keeping from her.',
 'The talisman Rya leaves behind at the end of her quest suggests that her mother was Daedicar.',
 'Daedicar was a woman who was said to have birthed multiple grotesque children.',
 'Daedicar birthed multiple grotesque children as a result of committing countless acts of adultery.',
 'Patches the Untethered is a bandit.',
 'Patches the Untethered tricks unsuspecting people into various death traps.',
 'Patches the Untethered tricks unsuspecting people into entrapment schemes.',
 'Diallos is the youngest son of House Hoslow.',
 'Jar-Bairn is a young jar living in Jarburg.',
 'Jar-Bairn is one of the few living Jars capable of speaking to the Tarnished.',
 'Jar-Bairn is a warrior jar.',
 'Jar-Bairn has an uncle named Alexander.',
 'The Tarnished may find Jar-Bairn talking in his sleep.',
 'Jar-Bairn dreams about reuniting with Alexander.',
 'Jar-Bairn dreams about telling Alexander that he is a warrior jar too.',
 'Jar-Bairn dreams about poachers destroying the Living Pots at Jarburg.',
 'Jar-Bairn dreams about Diallos taking care of him.',
 'Iron Fist Alexander is an older Living Jar.',
 'Iron Fist Alexander left his home of Jarburg to seek great battle.',
 'Iron Fist Alexander left his home of Jarburg to hone his combat skills.',
 'Iron Fist Alexander is a warrior jar.',
 'Blackguard Big Boggart is a Tarnished and former criminal.',
 'Blackguard Big Boggart sells boiled prawns and crabs at the Boilprawn Shack.',
 'Blackguard Big Boggart also sells boiled prawns and crabs just outside the royal capital.',
 'It is possible that Blackguard Big Boggart was previously convicted for thievery.',
 "Blackguard Big Boggart stole Rya's necklace when the Tarnished meets Blackguard Big Boggart.",
 'Blackguard Big Boggart used to be cellmates with Dung Eater.',
 'Blackguard Big Boggart witnessed Dung Eater defile the body of his friend with the Seedbed Curse.',
 'Witnessing Dung Eater defile the body of his friend with the Seedbed Curse was the most harrowing experience Blackguard Big Boggart had ever had.',
 'Dung Eater is a Tarnished.',
 "Dung Eater's armor suggests that he bears the heart of an Omen.",
 'Dung Eater was a merciless killer even before being brought back to the Lands Between.',
 'Dung Eater would defile the corpses of those he killed with Seedbed Curses.',
 'Dung Eater would curse the souls of those he killed to never be able to return to the Erdtree.',
 "Dung Eater's biggest aspiration is to defile and curse everyone in the Lands Between.",
 "Dung Eater's biggest aspiration is to curse all future generations.",
 "Dung Eater's dream can be realized by aiding him in gestating the Mending Rune of the Fell Curse.",
 'Enia is a Finger Reader that the Tarnished encounters at the Roundtable Hold.',
 'Enia is an agent of the Greater Will.',
 'Enia is supportive of the Tarnished burning down the Erdtree when her Two Fingers stop communicating with her.',
 'Enia claims that before the Tarnished, another had gathered 2 Great Runes.',
 'Queen Marika, the Eternal is a Numen.',
 'Queen Marika was chosen and brought from her homeland to the Lands Between by the Greater Will.',
 'Queen Marika served as a vassal to the Greater Will.',
 'Queen Marika was gifted Maliketh as a Shadow.',
 "Maliketh is Queen Marika's half-brother.",
 'Queen Marika entrusted the Rune of Death to Maliketh when the Golden Order was established.',
 'Queen Marika had two consorts during her reign.',
 "Queen Marika's first consort was Godfrey.",
 'Queen Marika and Godfrey had three children together.',
 "Queen Marika's children are Godwyn the Golden and the Omen twins, Morgott and Mohg.",
 'Queen Marika and her followers waged wars against several factions and gods in the Lands Between.',
 'Queen Marika waged wars on behalf of the Greater Will.',
 'The most notable factions and gods that Queen Marika waged wars against include the Storm Lord, the fire giants and their god, the One-Eyed God, the Academy of Raya Lucaria, and the Carian royal family.',
 'It is unclear which side instigated the war against the Dragons.',
 'Queen Marika waged wars against the Godskin Apostles and their god, the Gloam-Eyed Queen.',
 'The war against the Giants ended in favor of Queen Marika.',
 'Queen Marika realized that she would be unable to extinguish the flame at the Forge of the Giants.',
 "The flame at the Forge of the Giants is the fabled 'flame of ruin' strong enough to burn the Erdtree.",
 'Queen Marika cursed the final Fire Giant survivor to protect the forge for all eternity.',
 'When the last war was finally over, Queen Marika took the blessing of grace from Godfrey and his warriors.',
 'Godfrey and his warriors were turned into Tarnished by Queen Marika.',
 'Queen Marika exiled Godfrey and his warriors from the Lands Between.',
 'Queen Marika took Radagon to be her second consort.',
 'Queen Marika had twins Miquella and Malenia with Radagon.',
 'At some point, Queen Marika started to harbor doubts towards the Greater Will and the Golden Order.',
 'It is speculated that Queen Marika had a hand in the Night of the Black Knives.',
 'Queen Marika is rumored to have a connection with the Black Knife Assassins.',
 "Queen Marika's final act of rebellion against the Greater Will was the shattering of the Elden Ring.",
 "The shattering of the Elden Ring caused Queen Marika's imprisonment within the Erdtree.",
 'The shattering of the Elden Ring caused the war between the demigods.',
 'Radagon of the Golden Order is characterized by his flowing red locks.',
 "Radagon is Queen Marika's second chosen consort.",
 'Radagon is a great warrior.',
 'The early life of Radagon remains a mystery.',
 'It is unclear how Radagon became a prominent figure in the Golden Order.',
 'There is speculation that Radagon may be a smaller-sized Fire Giant.',
 "The speculation about Radagon being a Fire Giant comes from the descriptions of the Sword of Milos and Giant's Red Braid.",
 'Another theory suggests that Radagon was cursed to have red hair by the Fire Giants.',
 "The curse was a result of the Golden Order's war with the Fire Giants.",
 'Radagon was said to have hated the red-tint of his hair.',
 "In the war against Liurnia of the Lakes, Radagon was tasked by Queen Marika to lead the Erdtree's armies.",
 'The sword monuments that the Tarnished can find in Liurnia suggest that there were two Liurnian Wars.',
 'It was after the second Liurnian War that Radagon and Rennala fell in love.',
 'Radagon sought absolution at the Church of Vows using Celestial Dew.',
 'Radagon and Rennala were bonded by marriage.',
 'The marriage united the Capital of Leyndell and the Academy of Raya Lucaria.',
 'The Glintstone Kris is one of the symbols of the unity of the Capital of Leyndell and the Academy of Raya Lucaria.',
 'As is tradition, Rennala bestowed a Moon Greatsword onto Radagon, her spouse.',
 'Radagon and Rennala bore three children: General Radahn, Praetor Rykard, and Lunar Princess Ranni.',
 'Radagon gifted Rennala an Amber Egg.',
 "Radagon left Rennala to join Marika's side when Godfrey and his fellow Tarnished were exiled from the Lands Between.",
 'Radagon and Marika had twin demigods named Miquella and Malenia.',
 'Radagon reforged his Moon Greatsword into the Golden Order Greatsword.',
 "The requirement of both Faith and Intelligence in casting Golden Order Incantations is speculated to be due to Radagon's learning sorceries while being Rennala's consort.",
 'Radagon learned incantations when he was consort to Queen Marika.',
 'A statue in the Royal Capital reveals that Marika and Radagon are one and the same.',
 'It is unclear whether Marika and Radagon were always one.',
 'It is unclear whether Radagon is a fragment of Marika.',
 "Melina's dialogue suggests that Marika and Radagon became one after becoming consorts.",
 'Despite being one and the same person, Marika and Radagon held different wills.',
 'When Marika shattered the Elden Ring, Radagon used the same hammer that Marika used to try to repair it.',
 'Godfrey was the first consort to Queen Marika.',
 'Godfrey was the first Elden Lord.',
 'Godfrey and Queen Marika had 3 children together.',
 'The children of Godfrey and Queen Marika are Godwyn the Golden and the Omen twins, Morgott and Mohg.',
 'Godfrey was originally known as Hoarah Loux.',
 'Hoarah Loux was a fierce warrior with a strong bloodlust.',
 'Hoarah Loux was the chieftain of the badlands.',
 "Upon being selected as Queen Marika's first consort, Godfrey took Beast Regent Serosh upon his back.",
 'Godfrey took Beast Regent Serosh upon his back to quell his insatiable bloodlust.',
 'Godfrey needed to be more befitting of a Lord.',
 'When the Golden Order was established, Godfrey was tasked with leading several wars.',
 "Godfrey's wars were to further the influence of the Golden Order.",
 'One of the wars led by Godfrey was against the Giants.',
 'Godfrey faced the Storm Lord alone.',
 "During Godfrey's reign, gladiatorial combat in colosseums all over the Lands Between was commonplace.",
 'The gladiatorial combat was held as rituals to honor the Erdtree.',
 "The practice of gladiatorial combat died out when Radagon became Queen Marika's next consort.",
 'After Godfrey won his last campaign, there were no worthy opponents left to battle with.',
 "Marika took away the Erdtree's blessing from Godfrey and countless others.",
 "Marika's action turned Godfrey and countless others into Tarnished.",
 'Godfrey led the Tarnished out of the Lands Between.',
 'The journey led by Godfrey is referred to as the Long March.',
 "Godfrey's axe was broken in a battle during the Long March.",
 'After the Long March ended, Godfrey reverted back to becoming a simple warrior.',
 'Godfrey still carried Serosh on his back after reverting to a simple warrior.',
 'Rennala is known as Queen of the full moon.',
 'Rennala was a young astrologer.',
 'Rennala would always gaze up at the stars.',
 'Rennala had a chance encounter with the Full Moon.',
 'Rennala learnt of the magic of the Full Moon.',
 'Rennala became one of the most powerful glintstone sorcerers.',
 "Rennala's new mastery over lunar magic bewitched the Academy of Raya Lucaria.",
 'Rennala became the head of the Academy of Raya Lucaria.',
 'Rennala became the head of the Glintstone Knights.',
 'Rennala established the Carian family as royalty.',
 "Rennala met one of the Erdtree's champions, Radagon.",
 'Rennala fought against Radagon.',
 'Rennala and Radagon fell in love.',
 'Rennala and Radagon reconciled at the Church of Vows.',
 'Rennala bestowed upon Radagon a Moon Greatsword.',
 "Rennala and Radagon's union bore three children.",
 'One night, Rennala took Ranni out stargazing.',
 'Rennala took Ranni out stargazing as she did in her childhood.',
 "Rennala was devastated by Radagon's return to Marika's side.",
 "Rennala grew weak after Radagon's return to Marika's side.",
 "Rennala's charm over the Academy of Raya Lucaria fell.",
 'Rennala ended up being locked up in the Grand Library.',
 'The Tarnished finds Rennala cradling the Amber Egg.',
 'Morgott is the omen king.',
 'Morgott is one of two Omen twins.',
 'Morgott was born of Queen Marika.',
 'Morgott was born of Godfrey.',
 'Morgott ruled the capital in the shadows as the Unveiled Monarch.',
 'During the Second Defense of Leyndell, Morgott successfully defended the capital.',
 'During the Second Defense of Leyndell, Morgott successfully defended the Erdtree from his fellow invading demigods.',
 "Morgott's dialogue suggests he attempted to claim the throne of the Elden Lord.",
 'The Tarnished will first encounter Morgott under the pseudonym, Margit.',
 'Morgott prevents the Tarnished from challenging Godrick in Stormveil Castle.',
 'Morgott prevents the Tarnished from obtaining one of many Great Runes required to enter the capital.',
 'Mohg is known as Lord of Blood.',
 'Rykard is known as the Lord of Blasphemy.',
 'Praetor Rykard is the Lord of the Volcano Manor.',
 'Praetor Rykard is a ruthless justiciar.',
 'Praetor Rykard is the son of Rennala and Radagon.',
 "Praetor Rykard became a demigod after Radagon's unity with Queen Marika.",
 'Rykard presides over Mt. Gelmir.',
 'Rykard was served by the Gelmir Knights.',
 'The lava sorceries that the Tarnished can learn were created by Rykard.',
 'Some of the lava sorceries are old hexes from Mt. Gelmir that Rykard turned into practical sorceries.',
 'At some point, Rykard met Tanith in a foreign land.',
 'Rykard brought Tanith back to the Lands Between to be his consort.',
 'Rykard had a hand in the Night of the Black Knives.',
 "The extent of Rykard's involvement in the Night of the Black Knives is unclear.",
 "The Blasphemous Claw was an item rewarded by Rykard's sister Ranni.",
 'Rykard used the Blasphemous Claw to challenge Maliketh as a last resort.',
 "The description for the Taker's Cameo implies that Rykard believed that Marika and her Order ruled by force.",
 'Rykard swore himself to blasphemy.',
 'Rykard sought to overthrow Marika and her Order.',
 "Rykard's ambition drew many towards him.",
 'The ancient people of Mt. Gelmir worshipped a powerful serpent god.',
 'The ancient people of Mt. Gelmir offered sacrifices to the powerful serpent god.',
 'Rykard encountered the God-Devouring Serpent.',
 'Rykard offered himself and his Great Rune as sacrifices to the God-Devouring Serpent.',
 "Rykard's sacrifice granted him immortality.",
 "Rykard's immortality allowed him to grow and devour people and gods alike for all eternity.",
 "Rykard's fall into greed and glutinous depravity caused most of his followers to turn against him.",
 'Tanith was a notable exception among those who turned against Rykard.',
 'The former Gelmir Knights sought out the Serpent-Hunter.',
 'The Serpent-Hunter is a great spear designed to hunt the immortal serpent.',
 'The former Gelmir Knights sought to put an end to their Lord, Rykard.',
 'The former Gelmir Knights found the mythical weapon, the Serpent-Hunter.',
 'The former Gelmir Knights were unsuccessful in defeating Rykard.',
 "Corpses holding the Serpent-Hunter are found in Rykard's boss room.",
 "When the Tarnished visits the Volcano Manor, they find its members following Rykard's blasphemous path.",
 'It is later revealed that those who proved themselves as recusants were granted an audience with Rykard.',
 "Recusants became part of Rykard's family by being devoured by the great serpent himself.",
 'It seems that the content you would like me to decompose is missing.']